SELECT
    YEAR,
    CATEGORY,
    SUPPLIER,
    MATERIAL,
    CLEANSHEET_OPPORTUNITY,
    PRICE_ARBITRAGE,
    SUPPLIER_SAVINGS,
    OEM_NON_OEM_OPPORTUNITY,
    HCC_TO_LCC_OPPORTUNITY,
    POTENTIAL_SAVINGS_BY_STANDARDIZATION,
    EARLY_PAYMENT_OPPORTUNITY,
    DISCOUNT_NOT_USED,
    TOTAL_OPPORTUNITY
FROM
    DATA.T_C_TOTAL_SAVINGS_OPPORTUNITY
WHERE YEAR = YEAR(CURRENT_DATE)
AND LOWER(CATEGORY) = LOWER('Bearings')