WITH SELECTED_PERIOD_DATA AS (
    SELECT
        QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        MIN(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS MIN_DATE,
        MAX(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS MAX_DATE
    FROM
        DATA.VT_DIM_PERIOD AS PER
    WHERE
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
        AND QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = QUARTER(CURRENT_DATE)
    GROUP BY
        QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD'))
),
SELECTED_QUARTER_MONTH_SHOULD_COST_DATA AS (
    SELECT
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS QUARTER,
        TXT_CATEGORY_LEVEL_2,
        MAT.TXT_MATERIAL AS MATERIAL,
        ARCH.TXT_ARCHETYPE AS ARCHTYPE,
        SUM(FIS.MES_SHOULD_COST) AS SELECTED_PERIOD_SHOULD_COST
    FROM
        DATA.VT_FACT_ICM_SHOULDCOST FIS
        JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = FIS.DIM_DATE
        JOIN DATA.VT_DIM_ICM_ARCHETYPE_INDEX_MAPPING IAIM ON IAIM.DIM_COMBINATION_KEY = FIS.DIM_COMBINATION_KEY
        JOIN DATA.VT_DIM_ICM_ARCHETYPE ARCH ON ARCH.DIM_ARCHETYPE = IAIM.DIM_ARCHETYPE
        JOIN DATA.VT_DIM_ICM_MAPPING ICM ON IAIM.DIM_ARCHETYPE = ICM.DIM_ARCHETYPE
        JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = ICM.DIM_MATERIAL
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME ST ON ST.DIM_SOURCING_TREE = ICM.DIM_SOURCING_TREE
    WHERE
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) IN (
            SELECT
                YEAR(MIN_DATE)
            FROM
                SELECTED_PERIOD_DATA
        )
        AND MONTH(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) IN (
            SELECT
                MONTH(MIN_DATE)
            FROM
                SELECTED_PERIOD_DATA
        )
    GROUP BY
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        TXT_CATEGORY_LEVEL_2,
        MAT.TXT_MATERIAL,
        ARCH.TXT_ARCHETYPE
),
PREVIOUS_YEAR_LAST_MONTH_SHOULD_COST_DATA AS (
    SELECT
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        TXT_CATEGORY_LEVEL_2,
        MAT.TXT_MATERIAL AS MATERIAL,
        ARCH.TXT_ARCHETYPE AS ARCHTYPE,
        SUM(FIS.MES_SHOULD_COST) AS PREVIOUS_PERIOD_SHOULD_COST
    FROM
        DATA.VT_FACT_ICM_SHOULDCOST FIS
        JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = FIS.DIM_DATE
        JOIN DATA.VT_DIM_ICM_ARCHETYPE_INDEX_MAPPING IAIM ON IAIM.DIM_COMBINATION_KEY = FIS.DIM_COMBINATION_KEY
        JOIN DATA.VT_DIM_ICM_ARCHETYPE ARCH ON ARCH.DIM_ARCHETYPE = IAIM.DIM_ARCHETYPE
        JOIN DATA.VT_DIM_ICM_MAPPING ICM ON IAIM.DIM_ARCHETYPE = ICM.DIM_ARCHETYPE
        JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = ICM.DIM_MATERIAL
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME ST ON ST.DIM_SOURCING_TREE = ICM.DIM_SOURCING_TREE
    WHERE
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) IN (
            SELECT
                YEAR(MIN_DATE)-1
            FROM
                SELECTED_PERIOD_DATA
        )
        AND MONTH(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = 12
    GROUP BY
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        TXT_CATEGORY_LEVEL_2,
        MAT.TXT_MATERIAL,
        ARCH.TXT_ARCHETYPE
)
SELECT
    SMSC.YEAR,
    SMSC.QUARTER,
    SMSC.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
    SMSC.MATERIAL AS MATERIAL,
    SMSC.ARCHTYPE,
    SMSC.SELECTED_PERIOD_SHOULD_COST,
    PMSC.PREVIOUS_PERIOD_SHOULD_COST,
    ROUND(
        (
            SMSC.SELECTED_PERIOD_SHOULD_COST - PMSC.PREVIOUS_PERIOD_SHOULD_COST
        ),
        2
    ) AS DIFF_SHOULD_COST,
    ROUND(
        (
            (
                (
                    PMSC.PREVIOUS_PERIOD_SHOULD_COST - SMSC.SELECTED_PERIOD_SHOULD_COST
                ) * 100
            ) / SMSC.SELECTED_PERIOD_SHOULD_COST
        ),
        5
    ) AS MARKET_VOLATILITY_PERCENTAGE
FROM
    SELECTED_QUARTER_MONTH_SHOULD_COST_DATA SMSC
    JOIN PREVIOUS_YEAR_LAST_MONTH_SHOULD_COST_DATA PMSC ON SMSC.ARCHTYPE = PMSC.ARCHTYPE
    AND SMSC.TXT_CATEGORY_LEVEL_2 = PMSC.TXT_CATEGORY_LEVEL_2 AND
    SMSC.MATERIAL = PMSC.MATERIAL
ORDER BY SMSC.YEAR,
SMSC.QUARTER,
SMSC.TXT_CATEGORY_LEVEL_2