WITH DIFFPAYMENT AS (
SELECT 
    YEAR(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) AS YEAR,
    SUP.TXT_CONS_SUPPLIER_L1,
	IP.MES_DIFF_EARLY_PAYMENT,
	SUM(IP.MES_SPEND_PAID_CURR_1) AS TOTAL_SPEND,
	CASE WHEN COUNT(MES_INTEGER)>0 THEN
	SUM(MES_DIFF_EARLY_PAYMENT) / NULLIF(COUNT(MES_INTEGER), 0) 
	ELSE 0 END AS DIFF_EARLY_PAYMENT
FROM 
    DATA.VT_C_FACT_INVOICEPOSITION_PAYMENT AS IP
	JOIN DATA.VT_C_DIM_SUPPLIER AS SUP ON SUP.DIM_SUPPLIER=IP.DIM_SUPPLIER
	JOIN DATA.VT_DIM_PAYMENTTERM AS PT ON PT.DIM_PAYMENT_TERM = IP.DIM_PAYMENT_TERM
    JOIN DATA.VT_C_DIM_VALUETYPE AS VT ON VT.DIM_VALUE_TYPE = IP.DIM_VALUE_TYPE
    JOIN DATA.VT_DIM_PERIOD VDP ON VDP.DIM_DATE = IP.DIM_DATE
    WHERE VT.DIM_VALUE_TYPE = 'P' AND LOWER(PT.TXT_PAYMENT_TERM_TYPE) = LOWER('NET PAYMENT')
    AND YEAR(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) = '2022'
    GROUP BY 
		SUP.TXT_CONS_SUPPLIER_L1,
		IP.MES_DIFF_EARLY_PAYMENT,
        YEAR(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD'))
		)
SELECT YEAR, DP.TXT_CONS_SUPPLIER_L1 AS SUPPLIER,
	TOTAL_SPEND,
	DIFF_EARLY_PAYMENT,
	CASE WHEN DP.MES_DIFF_EARLY_PAYMENT < -3 
	THEN (DP.TOTAL_SPEND * DP.DIFF_EARLY_PAYMENT * -1) / 365
	ELSE 0
	END
	AS EARLY_PAYMENT
FROM DIFFPAYMENT AS DP
ORDER BY EARLY_PAYMENT DESC