SELECT
    YEAR,
    CATEGORY,
    SUPPLIER,
    CLEANSHEET_OPPORTUNITY,
    PRICE_ARBITRAGE,
    SUPPLIER_SAVINGS,
    OEM_NONOEM_OPPORTUNITY,
    HCC_TO_LCC_OPPORTUNITY,
    PAYMENT_TERMS_STANDARDIZATION_SAVINGS,
    EARLY_PAYMENT_OPPORTUNITY,
    DISCOUNT_NOT_USED,
    SUM_MAX_OPPORTUNITY
FROM
    T_C_TOTAL_SAVINGS_OPPORTUNITY
WHERE YEAR = YEAR(CURRENT_DATE)