WITH BASE_TABLE AS (
    SELECT
        YEAR(TO_DATE(B.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        B.TXT_MONTH,
        NULLIF(C.TXT_MATERIAL, 'MATERIAL') TXT_MATERIAL,
        NULLIF(A.DIM_MATERIAL, '1') DIM_MATERIAL,
        A.DIM_SUPPLIER,
        D.TXT_CONS_SUPPLIER_L1,
        E.TXT_COUNTRY,
        F.TXT_INCOTERM_ABB,
        SUM(A.MES_SPEND_CURR_1) AS SPEND,
        SUM(A.MES_QUANTITY) AS QUANTITY,
        CASE
            WHEN SUM(A.MES_QUANTITY) > 0 THEN SUM(A.MES_SPEND_CURR_1) / SUM(A.MES_QUANTITY)
            ELSE 0
        END AS PRICE_AVG
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED A
        JOIN DATA.VT_DIM_PERIOD B ON A.DIM_DATE = B.DIM_DATE
        JOIN DATA.VT_C_DIM_MATERIAL C ON C.DIM_MATERIAL = A.DIM_MATERIAL
        JOIN DATA.VT_C_DIM_SUPPLIER D ON D.DIM_SUPPLIER = A.DIM_SUPPLIER
        JOIN DATA.VT_DIM_SUPPLIERCOUNTRY E ON E.DIM_COUNTRY = A.DIM_COUNTRY
        JOIN DATA.VT_DIM_INCOTERM F ON F.DIM_INCOTERM = A.DIM_INCOTERM
    WHERE
        YEAR(TO_DATE(B.DIM_DATE, 'YYYYMMDD')) = '2023'
        AND A.DIM_MATERIAL <> '-1'
    GROUP BY
        B.TXT_MONTH,
        C.TXT_MATERIAL,
        A.DIM_MATERIAL,
        A.DIM_SUPPLIER,
        D.TXT_CONS_SUPPLIER_L1,
        E.TXT_COUNTRY,
        F.TXT_INCOTERM_ABB,
        YEAR(TO_DATE(B.DIM_DATE, 'YYYYMMDD'))
    HAVING
        SUM(A.MES_SPEND_CURR_1) > 0
        AND SUM(A.MES_QUANTITY) > 0
),
MIN_PRICE_TABLE AS (
    SELECT
        YEAR,
        DIM_MATERIAL,
        TXT_COUNTRY,
        TXT_INCOTERM_ABB,
        MIN(PRICE_AVG) MIN_AVG_PRICE
    FROM
        BASE_TABLE
    GROUP BY
        DIM_MATERIAL,
        TXT_COUNTRY,
        TXT_INCOTERM_ABB,
        YEAR
),
MIN_PRICE_AVG AS (
    SELECT
        A.YEAR,
        A.TXT_MONTH,
        A.TXT_MATERIAL,
        A.DIM_MATERIAL,
        A.TXT_CONS_SUPPLIER_L1,
        A.TXT_COUNTRY,
        A.TXT_INCOTERM_ABB,
        SPEND,
        QUANTITY,
        PRICE_AVG AS PRICE_AVERAGE,
        MIN_AVG_PRICE
    FROM
        BASE_TABLE A
        JOIN MIN_PRICE_TABLE B ON A.DIM_MATERIAL = B.DIM_MATERIAL
        AND A.TXT_COUNTRY = B.TXT_COUNTRY
        AND A.TXT_INCOTERM_ABB = B.TXT_INCOTERM_ABB
),
PRICE_ARB_TBL AS (
    SELECT
        YEAR,
        TXT_MONTH,
        TXT_MATERIAL,
        DIM_MATERIAL,
        TXT_CONS_SUPPLIER_L1,
        TXT_COUNTRY,
        TXT_INCOTERM_ABB,
        SPEND,
        QUANTITY,
        PRICE_AVERAGE,
        MIN_AVG_PRICE,
        ROUND((SPEND - (QUANTITY * MIN_AVG_PRICE)), 2) AS PRICE_ARBITRAGE,
        CONCAT(
            ROUND(
                (
                    (SPEND - (QUANTITY * MIN_AVG_PRICE)) * 100 / SPEND
                ),
                2
            ),
            '%'
        ) AS PRICE_ARBITRAGE_PERCENTAGE
    FROM
        MIN_PRICE_AVG
)
SELECT
    ROUND(SUM(PRICE_ARBITRAGE), 2) AS TOTAL_OPPORTUNITY
FROM
    PRICE_ARB_TBL