	WITH TOTAL_SPEND AS (
		SELECT
			YEAR(TO_DATE(P.DIM_DATE, 'YYYYMMDD')) AS YEAR,
			QUARTER(TO_DATE(P.DIM_DATE, 'YYYYMMDD')) AS QUARTER,
			MONTH(TO_DATE(P.DIM_DATE, 'YYYYMMDD')) AS MONTH,
			SUM(MES_SPEND_CURR_1) AS TOTAL_SPEND,
			SUM(MES_SPEND_CURR_1) * 0.25 AS DESIRED_OEM_SPEND,
			T2.TXT_CONS_SUPPLIER_L1 AS SUPPLIER,
			ST.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
			MAT.TXT_MATERIAL,
			MAT.DIM_MATERIAL,
			T1.DIM_SOURCING_TREE,
			SC.TXT_COUNTRY,
			T1.DIM_COUNTRY,
			T2.TXT_OEM_TYPE,
			T2.DIM_SUPPLIER,
			G.TXT_PLANT,
			T1.DIM_PLANT,
			COM.TXT_LEVEL_4
		FROM
			DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED T1
			LEFT OUTER JOIN DATA.VT_C_DIM_SUPPLIER T2 ON T1.DIM_SUPPLIER = T2.DIM_SUPPLIER
			LEFT OUTER JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME ST ON ST.DIM_SOURCING_TREE = T1.DIM_SOURCING_TREE
			LEFT OUTER JOIN DATA.VT_DIM_PERIOD P ON T1.DIM_DATE = P.DIM_DATE
			LEFT OUTER JOIN DATA.VT_DIM_SUPPLIERCOUNTRY SC ON T1.DIM_COUNTRY = SC.DIM_COUNTRY
			LEFT OUTER JOIN DATA.VT_C_DIM_MATERIAL MAT ON T1.DIM_MATERIAL = MAT.DIM_MATERIAL
			LEFT OUTER JOIN DATA.VT_DIM_PLANT G ON G.DIM_PLANT = T1.DIM_PLANT
			LEFT OUTER JOIN DATA.VT_DIM_COMPANY COM ON T1.DIM_COMPANY = COM.DIM_COMPANY
		WHERE
			TXT_OEM_TYPE <> ''
			AND G.TXT_PLANT <> '#'
			AND T1.DIM_MATERIAL <> '-1'
		GROUP BY
			T2.TXT_CONS_SUPPLIER_L1,
			T2.TXT_OEM_TYPE,
			T2.DIM_SUPPLIER,
			YEAR(TO_DATE(P.DIM_DATE, 'YYYYMMDD')),
			QUARTER(TO_DATE(P.DIM_DATE, 'YYYYMMDD')),
			MONTH(TO_DATE(P.DIM_DATE, 'YYYYMMDD')),
			SC.TXT_COUNTRY,
			T1.DIM_COUNTRY,
			MAT.TXT_MATERIAL,
			MAT.DIM_MATERIAL,
			ST.TXT_CATEGORY_LEVEL_2,
			T1.DIM_SOURCING_TREE,
			G.TXT_PLANT,
			T1.DIM_PLANT,
			COM.TXT_LEVEL_4
	),
	OEM_SPEND AS (
		SELECT
			SUPPLIER AS OEM_SUPPLIER,
			TOTAL_SPEND AS TOTAL_OEM_SPEND,
			DIM_SUPPLIER,
			YEAR,
			QUARTER,
			MONTH,
			TXT_OEM_TYPE,
			TXT_COUNTRY,
			DIM_COUNTRY,
			CATEGORY,
			TXT_MATERIAL,
			DIM_MATERIAL,
			DIM_SOURCING_TREE,
			TXT_PLANT,
			DIM_PLANT,
			TXT_LEVEL_4
		FROM
			TOTAL_SPEND
		WHERE
			TXT_OEM_TYPE = 'OEM'
	),
	BASE_CALCULATIONS AS (
		SELECT
			TS.SUPPLIER,
			OE.TOTAL_OEM_SPEND,
			TS.TOTAL_SPEND,
			TS.YEAR,
			TS.QUARTER,
			TS.MONTH,
			TS.TXT_OEM_TYPE,
			TS.TXT_COUNTRY,
			TS.DIM_COUNTRY,
			TS.TXT_MATERIAL,
			TS.CATEGORY,
			TS.DIM_SOURCING_TREE,
			TS.TXT_PLANT,
			TS.DIM_PLANT,
			TS.TXT_LEVEL_4,
			DESIRED_OEM_SPEND,
			CASE
				WHEN TS.DESIRED_OEM_SPEND > OE.TOTAL_OEM_SPEND THEN OE.TOTAL_OEM_SPEND
				ELSE TS.DESIRED_OEM_SPEND
			END AS HELPER_REAL_OEM,
			CASE
				WHEN TS.TOTAL_SPEND = 0 THEN 0
				ELSE (OE.TOTAL_OEM_SPEND / TS.TOTAL_SPEND)
			END AS OEM_PERCENTAGE_OF_TOTAL,
			CASE
				WHEN (OE.TOTAL_OEM_SPEND -(0.4 * TS.TOTAL_SPEND)) < 0 THEN 0
				ELSE (OE.TOTAL_OEM_SPEND - (0.4 * TS.TOTAL_SPEND))
			END AS OEM_BENCHMARK_SAVING
		FROM
			TOTAL_SPEND TS
			LEFT OUTER JOIN OEM_SPEND OE ON OE.DIM_SUPPLIER = TS.DIM_SUPPLIER
			AND OE.YEAR = TS.YEAR
			AND TS.DIM_COUNTRY = OE.DIM_COUNTRY
			AND TS.DIM_PLANT = OE.DIM_PLANT
			AND TS.DIM_SOURCING_TREE = OE.DIM_SOURCING_TREE
			AND TS.DIM_MATERIAL = OE.DIM_MATERIAL
	),
	BENCHMARK_VALUE AS (
		SELECT
			SUPPLIER,
			YEAR,
			QUARTER,
			MONTH,
			TOTAL_OEM_SPEND,
			DESIRED_OEM_SPEND,
			TOTAL_SPEND,
			TXT_OEM_TYPE,
			TXT_COUNTRY,
			CATEGORY,
			TXT_MATERIAL,
			DIM_SOURCING_TREE,
			OEM_BENCHMARK_SAVING,
			OEM_PERCENTAGE_OF_TOTAL,
			HELPER_REAL_OEM,
			SUM(HELPER_REAL_OEM) OVER (PARTITION BY SUPPLIER, YEAR, CATEGORY) AS NEW_OEM,
			SUM(TOTAL_SPEND) OVER (PARTITION BY YEAR, CATEGORY) AS TOTAL,
			TXT_PLANT,
			TXT_LEVEL_4,
			(OEM_BENCHMARK_SAVING * 0.05) AS ABS_VALUE
		FROM
			BASE_CALCULATIONS
		WHERE ABS_VALUE is not NULL
	)
	SELECT
		YEAR,
		CATEGORY,
		TXT_COUNTRY AS COUNTRY,
		SUM(TOTAL_OEM_SPEND) AS OEM_SPEND,
		SUM(TOTAL_SPEND) AS SPEND,
		(SUM(TOTAL_SPEND) - SUM(TOTAL_OEM_SPEND)) AS NON_OEM_SPEND,
		SUM(OEM_BENCHMARK_SAVING) AS OEM_BENCHMARK_SAVING,
		SUM(ABS_VALUE) AS OEM_NONOEM_OPPORTUNITY
	FROM
		BENCHMARK_VALUE
	GROUP BY 
		YEAR,
		CATEGORY,
		TXT_COUNTRY
	ORDER BY
		OEM_NONOEM_OPPORTUNITY DESC