-- select * from data.news_insights where create_date=current_date()
WITH MONTHLY_SPEND AS (
    SELECT
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        MONTH(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS MONTH,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        COUNT(DISTINCT IVP.DIM_SUPPLIER) AS SUPPLIER_COUNT
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
        JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
    WHERE
        YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
    GROUP BY
        YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        MONTH(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2
    ORDER BY
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        MONTH(TO_DATE (PER.DIM_DATE, 'YYYYMMDD'))
)
SELECT
    YEAR,
    MONTH,
    CATEGORY,
    SUPPLIER_COUNT AS CURRENT_SUPPLIER_COUNT,
    LAG(SUPPLIER_COUNT) OVER (PARTITION BY CATEGORY ORDER BY YEAR, MONTH) AS PREVIOUS_SUPPLIER_COUNT,
    ROUND(
        CASE
            WHEN PREVIOUS_SUPPLIER_COUNT = 0 THEN 0
            ELSE ((CURRENT_SUPPLIER_COUNT - PREVIOUS_SUPPLIER_COUNT) / PREVIOUS_SUPPLIER_COUNT) * 100
        END,
        2
    ) AS MOM_GROWTH_PERCENTAGE
FROM
    MONTHLY_SPEND
ORDER BY
    YEAR,
    MONTH