SELECT
    SUM(fip.MES_SPEND_CURR_1 ) AS TotalSpend
FROM data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED fip
JOIN data.VT_C_DIM_Supplier  s ON fip.DIM_SUPPLIER=s.DIM_SUPPLIER 
WHERE
    s.TXT_OEM_TYPE  = 'OEM'