WITH BILL_RATE_DATA AS (
SELECT
    YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS YEAR,
    CATEGORY,
    TXT_GRADE AS ROLE,
    AVG(MES_PRICE_BENCHMARK) AS BILL_RATE
FROM
    DATA.VT_C_FACT_ACTUAL_BILL_RATES
WHERE 
    LOWER(CATEGORY) = LOWER('Marketing Svcs')
GROUP BY
    YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')),
    CATEGORY,
    TXT_GRADE
)
SELECT
    YEAR,
    CATEGORY,
    ROLE,
    BILL_RATE AS CURRENT_BILL_RATE,
    LAG (BILL_RATE) OVER (
        PARTITION BY
            ROLE
        ORDER BY
            YEAR
    ) AS PREVIOUS_BILL_RATE,
    ROUND(
        CASE
            WHEN PREVIOUS_BILL_RATE = 0 THEN 0
            ELSE ((CURRENT_BILL_RATE - PREVIOUS_BILL_RATE) / PREVIOUS_BILL_RATE) * 100
        END,
        2
    ) AS YOY_GROWTH_PERCENTAGE
FROM
    BILL_RATE_DATA
ORDER BY
    YEAR DESC, YOY_GROWTH_PERCENTAGE DESC