SELECT
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD'))AS Year,
	c.TXT_CATEGORY_LEVEL_2 AS Category,
	inc.TXT_INCOTERM AS Incoterm,
	COUNT(fip.DIM_INCOTERM) AS IncotermCount,
	SUM(fip.MES_SPEND_CURR_1) AS Spends
FROM
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED fip
JOIN data.VT_DIM_Incoterm inc ON
	inc.DIM_INCOTERM = fip.DIM_INCOTERM
JOIN data.VT_DIM_Period p ON
	p.DIM_DATE = fip.DIM_DATE
JOIN data.VT_DIM_SupplierStatus s ON
	s.DIM_SUPPLIER_STATUS = fip.DIM_SUPPLIER_STATUS
JOIN data.VT_C_DIM_ValueType v ON
	v.dim_value_type = fip.DIM_VALUE_TYPE
JOIN data.VT_C_DIM_SourcingTree_TECHCME c ON
	c.DIM_SOURCING_TREE = fip.DIM_SOURCING_TREE
WHERE
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
	AND 
        s.DIM_SUPPLIER_STATUS = 'E'
	AND 
        v.DIM_VALUE_TYPE = 'I'
	AND 
        c.TXT_CATEGORY_LEVEL_2 = 'Bearings'
GROUP BY YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')),
	c.TXT_CATEGORY_LEVEL_2,
	inc.TXT_INCOTERM