SELECT
    TO_DATE(per.DIM_DATE, 'YYYYMMDD') AS Year,
	pt.TXT_PAYMENT_TERM AS PaymentTerm,
	SUM(fip.MES_SPEND_CURR_1) AS TotalSpend,
	COUNT(DIM_INVOICE_POSITION) AS CountInvoicePosition
FROM
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED fip
JOIN data.VT_DIM_PaymentTerm pt 
ON pt.DIM_PAYMENT_TERM = fip.DIM_PAYMENT_TERM
JOIN data.VT_DIM_Period per ON per.DIM_DATE = fip.DIM_DATE
WHERE YEAR(TO_DATE(per.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
GROUP BY
	pt.TXT_PAYMENT_TERM, TO_DATE(per.DIM_DATE, 'YYYYMMDD')