SELECT
	YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS YEAR,
    TXT_BEROE_SUBCATEGORY AS CATEGORY,
	TXT_SEGMENTATION AS PRODUCT_TYPE,
	CONCAT(MAX(MES_VALUE), '%') AS REVENUE
FROM
	DATA.T_C_MARKET_DEMAND_SUPPLY_SEGMENTATION
WHERE
	LOWER(TXT_SEGMENTATION_TYPE) = LOWER('Industry Demand')
	AND LOWER(TXT_LOCATION) = LOWER('Global')
	AND YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
	AND LOWER(TXT_CATEGORY) = LOWER('Bearings')
GROUP BY 
	YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')),
    TXT_BEROE_SUBCATEGORY,
	TXT_SEGMENTATION
ORDER BY MAX(MES_VALUE) DESC