SELECT
    YEAR(TO_DATE (DIM_DATE, 'YYYYMMDD')) AS YEAR,
	TXT_CATEGORY AS CATEGORY,
    TXT_BEROE_SUBCATEGORY AS BEROE_CATEGORY,
    TXT_CRITERIA AS CRITERIA,
    ROUND(MAX(MES_VALUE), 2) AS MARKET_SIZE
FROM
    DATA.T_C_MARKET_ANALYSIS MA
WHERE
    LOWER(TXT_CRITERIA) LIKE LOWER('Total Market size ($)')
    AND LOWER(TXT_LOCATION) = LOWER('Global')
    AND YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD'))  = YEAR(CURRENT_DATE)
    AND LOWER(TXT_CATEGORY) = LOWER('Bearings')
GROUP BY
    YEAR(TO_DATE (DIM_DATE, 'YYYYMMDD')),
	TXT_CATEGORY,
    TXT_BEROE_SUBCATEGORY,
    TXT_CRITERIA
ORDER BY
	MAX(MES_VALUE) DESC