WITH CURRENT_QUARTER_DATA AS (
SELECT
	MIN(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS MIN_DATE,
	MAX(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS MAX_DATE
FROM
	DATA.VT_DIM_PERIOD VDP
WHERE
	YEAR(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
	AND QUARTER(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) = QUARTER(CURRENT_DATE)
), 
SELECTED_QUARTER_DATA AS (
    SELECT
        YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS YEAR,
        QUARTER(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS QUARTER,
        TXT_COMPONENT_NAME AS COMPONENT,
        TXT_BEROE_SUBCATEGORY AS BEROE_CATEGORY,
        AVG(MES_PRICE) AS PRICE
    FROM
        DATA.T_C_MARKET_PRICES AS MP
    WHERE
        TO_DATE(DIM_DATE, 'YYYYMMDD') >= (
            SELECT
                MIN_DATE
            FROM
                CURRENT_QUARTER_DATA
        )
        AND TO_DATE(DIM_DATE, 'YYYYMMDD') <= (
            SELECT
                MAX_DATE
            FROM
                CURRENT_QUARTER_DATA
        )
         AND LOWER(TXT_CATEGORY) = LOWER('Valves')
    GROUP BY
        YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')),
        QUARTER(TO_DATE(DIM_DATE, 'YYYYMMDD')),
        TXT_COMPONENT_NAME,
        TXT_BEROE_SUBCATEGORY
),
NEXT_3_MONTHS_QUARTER_DATA AS (
	SELECT
        YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS YEAR,
        QUARTER(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS QUARTER,
        TXT_COMPONENT_NAME AS COMPONENT,
        TXT_BEROE_SUBCATEGORY AS BEROE_CATEGORY,
        AVG(MES_PRICE) AS NEXT_PRICE
    FROM
        DATA.T_C_MARKET_PRICES AS MP
    WHERE
        TO_DATE(DIM_DATE, 'YYYYMMDD') >= (SELECT DATEADD(MONTH,3, MIN_DATE) FROM CURRENT_QUARTER_DATA)
        AND TO_DATE(DIM_DATE, 'YYYYMMDD') <= (SELECT DATEADD(MONTH,3, MAX_DATE) FROM CURRENT_QUARTER_DATA)
        AND LOWER(TXT_CATEGORY) = LOWER('Valves')
    GROUP BY
        YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')),
        QUARTER(TO_DATE(DIM_DATE, 'YYYYMMDD')),
        TXT_COMPONENT_NAME,
        TXT_BEROE_SUBCATEGORY
)
SELECT
	SQD.BEROE_CATEGORY AS CATEGORY,
	SQD.COMPONENT AS COMPONENT,
	SQD.YEAR AS CURRENT_YEAR,
	SQD.QUARTER AS CURRENT_QUARTER,
	ROUND(PRICE,2) AS CURRENT_COMPONENT_PRICE,
	NMD.YEAR AS NEXT_YEAR,
	NMD.QUARTER AS NEXT_QUARTER,
	ROUND(NEXT_PRICE,2) AS NEXT_3_MONTH_COMPONENT_PRICE,
	ROUND(((NEXT_PRICE-PRICE)/ PRICE)* 100, 2) AS NEXT_3_MONTH_COMPONENT_FORECAST,
	CONCAT(ROUND(((NEXT_PRICE-PRICE)/ PRICE)* 100, 2), '%') AS NEXT_3_MONTH_COMPONENT_FORECAST_PERCENTAGE
FROM
	SELECTED_QUARTER_DATA SQD
JOIN NEXT_3_MONTHS_QUARTER_DATA NMD
	ON
	SQD.COMPONENT = NMD.COMPONENT
	AND SQD.BEROE_CATEGORY = NMD.BEROE_CATEGORY