-- Steps To Create SQL
-- STEP 1: In Country Supplier Data, we get Year, Quarter, Category, Country, and Supplier for the current year and quarter where the category is 'Valves'.
-- STEP 2: In SKU Price Comparison, we will calculate the change in SKU price and market price for the current year and quarter for the suppliers fetched in STEP 1.
--
-- Context of this SQL: Find all the supplier who have SKU Price Percentage Change more than Market Price Percentage Change for the current year and quarter for the category 'Valves'.
WITH AVERAGE_PRICE_DATA AS (
    SELECT
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SC.TXT_COUNTRY AS COUNTRY,
        SUM(MES_SPEND_CURR_1) AS SPEND,
        SUM(MES_QUANTITY) AS QUANTITY,
        CASE WHEN SUM(MES_QUANTITY) > 0 THEN SUM(MES_SPEND_CURR_1)/SUM(MES_QUANTITY) ELSE 0 END AS AVERAGE_PRICE
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED AS IVP
        JOIN DATA.VT_DIM_PERIOD AS PER ON PER.DIM_DATE = IVP.DIM_DATE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME AS SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
        JOIN DATA.VT_DIM_SUPPLIERCOUNTRY AS SC ON SC.DIM_COUNTRY = IVP.DIM_COUNTRY
    WHERE
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
        AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
    GROUP BY
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        SC.TXT_COUNTRY
),
AVERAGE_SUPPLIER_PRICE_DATA AS (
    SELECT
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SC.TXT_COUNTRY AS COUNTRY,
        SUP.TXT_SUPPLIER AS SUPPLIER,
        SUM(MES_SPEND_CURR_1) AS SPEND,
        SUM(MES_QUANTITY) AS QUANTITY,
        CASE WHEN SUM(MES_QUANTITY) > 0 THEN SUM(MES_SPEND_CURR_1)/SUM(MES_QUANTITY) ELSE 0 END AS AVERAGE_PRICE_SUPPLIER
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED AS IVP
        JOIN DATA.VT_DIM_PERIOD AS PER ON PER.DIM_DATE = IVP.DIM_DATE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME AS SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
        JOIN DATA.VT_DIM_SUPPLIERCOUNTRY AS SC ON SC.DIM_COUNTRY = IVP.DIM_COUNTRY
        JOIN DATA.VT_C_DIM_SUPPLIER AS SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
    WHERE
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
        AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
    GROUP BY
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        SC.TXT_COUNTRY,
        SUP.TXT_SUPPLIER
)
SELECT 
    APD.YEAR,
    APD.CATEGORY,
    APD.COUNTRY,
    ASPD.SUPPLIER,
    AVERAGE_PRICE AS MARKET_PRICE,
    AVERAGE_PRICE_SUPPLIER AS SUPPLIER_PRICE
FROM 
    AVERAGE_PRICE_DATA APD
JOIN AVERAGE_SUPPLIER_PRICE_DATA ASPD ON APD.YEAR = ASPD.YEAR AND APD.CATEGORY = ASPD.CATEGORY AND APD.COUNTRY = ASPD.COUNTRY
WHERE AVERAGE_PRICE_SUPPLIER > AVERAGE_PRICE
ORDER BY AVERAGE_PRICE_SUPPLIER DESC