WITH SUPPLIER_SPEND AS (
    SELECT 
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SOUR.TXT_CATEGORY_LEVEL_4 AS SUBCATEGORY, 
        SUP.TXT_SUPPLIER AS SUPPLIER_NAME,
        SUM(IVP.MES_SPEND_CURR_1) AS SPEND
    FROM DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
    JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
    JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
    WHERE YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)-1
     AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Marketing Svcs')
    GROUP BY 
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        SOUR.TXT_CATEGORY_LEVEL_4,
        SUP.TXT_SUPPLIER
),
TOTAL_SPEND AS (
    SELECT 
        YEAR,
        CATEGORY,
        SUBCATEGORY,
        SUM(SPEND) AS TOTAL_SPEND
    FROM SUPPLIER_SPEND
    GROUP BY
        YEAR,
        CATEGORY,
        SUBCATEGORY
),
SUPPLIER_RANKED AS (
    SELECT 
        SUP.YEAR,
        SUP.CATEGORY,
        SUP.SUBCATEGORY,
        SUP.SUPPLIER_NAME,
        SUP.SPEND,
        TOTAL.TOTAL_SPEND,
        SUM(ROUND(SUP.SPEND,0)) OVER (PARTITION BY SUP.YEAR, SUP.CATEGORY, SUP.SUBCATEGORY ORDER BY ROUND(SUP.SPEND,0) DESC) AS CUMULATIVE_SPEND,
        (SUM(ROUND(SUP.SPEND,0)) OVER (PARTITION BY SUP.YEAR, SUP.CATEGORY, SUP.SUBCATEGORY ORDER BY ROUND(SUP.SPEND,0) DESC) / ROUND(TOTAL.TOTAL_SPEND,0)) * 100 AS CUMULATIVE_PERCENTAGE
    FROM SUPPLIER_SPEND SUP
    JOIN TOTAL_SPEND TOTAL ON SUP.YEAR = TOTAL.YEAR AND SUP.CATEGORY = TOTAL.CATEGORY AND SUP.SUBCATEGORY = TOTAL.SUBCATEGORY
)
SELECT 
    YEAR,
    CATEGORY,
    SUBCATEGORY,
    COUNT(DISTINCT SUPPLIER_NAME) AS TOTAL_SUPPLIERS,
    MAX(TOTAL_SPEND) AS TOTAL_SPEND,
    COUNT(DISTINCT CASE WHEN CUMULATIVE_PERCENTAGE <= 80 THEN SUPPLIER_NAME END)+1 AS KEY_SUPPLIERS,
    (TOTAL_SUPPLIERS-KEY_SUPPLIERS) AS TAIL_SUPPLIERS
FROM SUPPLIER_RANKED
GROUP BY YEAR,
    CATEGORY,
    SUBCATEGORY
ORDER BY TOTAL_SPEND DESC;