WITH MEDIA_DATA AS (
SELECT
    YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS YEAR,
    CATEGORY,
    TXT_MEDIA_NAME AS MEDIA_CHANNELS,
    AVG(MES_PRICE_BENCHMARK) AS PRICE
FROM
    DATA.VT_C_FACT_MEDIA_PRICE_BENCHMARK
WHERE 
    LOWER(CATEGORY) = LOWER('Marketing Svcs')
GROUP BY
    YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')),
    CATEGORY,
    TXT_MEDIA_NAME
)
SELECT
    YEAR,
    CATEGORY,
    MEDIA_CHANNELS,
    PRICE AS CURRENT_PRICE,
    LAG (PRICE) OVER (
        PARTITION BY
            MEDIA_CHANNELS
        ORDER BY
            YEAR
    ) AS PREVIOUS_PRICE,
    ROUND(
        CASE
            WHEN PREVIOUS_PRICE = 0 THEN 0
            ELSE ((CURRENT_PRICE - PREVIOUS_PRICE) / PREVIOUS_PRICE) * 100
        END,
        2
    ) AS YOY_GROWTH_PERCENTAGE
FROM
    MEDIA_DATA
ORDER BY
    YEAR DESC, YOY_GROWTH_PERCENTAGE DESC