WITH CURRENT_QUARTER AS (
SELECT
	MIN(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS MIN_DATE,
	MAX(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS MAX_DATE
FROM
	DATA.VT_DIM_PERIOD VDP
WHERE
	YEAR(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
	AND QUARTER(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) = QUARTER(CURRENT_DATE)
),
CURRENT_QUARTER_PRICE AS (
    SELECT
        YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')) AS YEAR,
        QUARTER (TO_DATE (DIM_DATE, 'YYYYMMDD')) AS QUARTER,
        TXT_CATEGORY AS CATEGORY,
        TXT_BEROE_SUBCATEGORY AS BEROE_CATEGORY,
        TXT_COMPONENT_NAME AS COMPONENT,
        AVG(MES_PRICE) AS PRICE
    FROM
        DATA.T_C_MARKET_PRICES
    WHERE
        TO_DATE (DIM_DATE, 'YYYYMMDD') >= (
            SELECT
                MIN_DATE
            FROM
                CURRENT_QUARTER_DATA
        )
        AND TO_DATE (DIM_DATE, 'YYYYMMDD') <= (
            SELECT
                MAX_DATE
            FROM
                CURRENT_QUARTER_DATA
        )
        AND LOWER(TXT_CATEGORY) = LOWER('CIBC')
    GROUP BY
        YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')),
        QUARTER (TO_DATE (DIM_DATE, 'YYYYMMDD')),
        TXT_CATEGORY,
        TXT_BEROE_SUBCATEGORY,
        TXT_COMPONENT_NAME
),
PREVIOUS_QUARTER_PRICE AS (
    SELECT
        YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')) AS YEAR,
        QUARTER (TO_DATE (DIM_DATE, 'YYYYMMDD')) AS QUARTER,
        TXT_CATEGORY AS CATEGORY,
        TXT_BEROE_SUBCATEGORY AS BEROE_CATEGORY,
        TXT_COMPONENT_NAME AS COMPONENT,
        AVG(MES_PRICE) AS PREVIOUS_PRICE
    FROM
        DATA.T_C_MARKET_PRICES
    WHERE
        AND TO_DATE(P.DIM_DATE, 'YYYYMMDD') <= (SELECT DATEADD(MONTH, -3, MAX_DATE) FROM CURRENT_QUARTER)
        AND TO_DATE(P.DIM_DATE, 'YYYYMMDD') >= (SELECT DATEADD(MONTH, -3, MIN_DATE) FROM CURRENT_QUARTER)
        AND LOWER(TXT_CATEGORY) = LOWER('CIBC')
    GROUP BY
        YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')),
        QUARTER (TO_DATE (DIM_DATE, 'YYYYMMDD')),
        TXT_CATEGORY,
        TXT_BEROE_SUBCATEGORY,
        TXT_COMPONENT_NAME
)
SELECT
    CQP.CATEGORY AS CATEGORY,
    CQP.BEROE_CATEGORY AS BEROE_CATEGORY,
    CQP.COMPONENT AS COMPONENT,
    ROUND(PRICE,2) AS CURRENT_PRICE, 
    ROUND(PREVIOUS_PRICE,2) AS PREVIOUS_PRICE,
    ROUND((PRICE - PREVIOUS_PRICE),2) AS PRICE_DIFF,
    CONCAT(ROUND(((PRICE - PREVIOUS_PRICE) / PREVIOUS_PRICE),2),'%') AS PERCENT_CHANGE
FROM CURRENT_QUARTER_PRICE CQP
JOIN PREVIOUS_QUARTER_PRICE PQP
    ON CQP.COMPONENT = PQP.COMPONENT
    AND CQP.CATEGORY = PQP.CATEGORY
    AND CQP.BEROE_CATEGORY = PQP.BEROE_CATEGORY
ORDER BY PERCENT_CHANGE DESC;