WITH
    FIVE_MONTH_SPEND AS (
        SELECT
            YEAR (TO_DATE (P.DIM_DATE, 'YYYYMMDD')) AS YEAR,
            SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
            S.TXT_SUPPLIER AS SUPPLIER,
            SUM(F.MES_SPEND_CURR_1) AS SPEND
        FROM
            DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED AS F
            JOIN DATA.VT_DIM_PERIOD AS P ON F.DIM_DATE = P.DIM_DATE
            JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = F.DIM_SOURCING_TREE
            JOIN DATA.VT_C_DIM_SUPPLIER AS S ON F.DIM_SUPPLIER = S.DIM_SUPPLIER
        WHERE
            TO_DATE (P.DIM_DATE, 'YYYYMMDD') <= '2023-12-31'
            AND TO_DATE (P.DIM_DATE, 'YYYYMMDD') >= '2023-08-01'
            AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
        GROUP BY
            YEAR (TO_DATE (P.DIM_DATE, 'YYYYMMDD')),
            SOUR.TXT_CATEGORY_LEVEL_2,
            S.TXT_SUPPLIER
    ),
    LAST_5_MONTH_SPEND AS (
        SELECT
            YEAR (TO_DATE (P.DIM_DATE, 'YYYYMMDD')) AS YEAR,
            SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
            S.TXT_SUPPLIER AS SUPPLIER,
            SUM(F.MES_SPEND_CURR_1) AS PREVIOUS_SPEND
        FROM
            DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED AS F
            JOIN DATA.VT_DIM_PERIOD AS P ON F.DIM_DATE = P.DIM_DATE
            JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = F.DIM_SOURCING_TREE
            JOIN DATA.VT_C_DIM_SUPPLIER AS S ON F.DIM_SUPPLIER = S.DIM_SUPPLIER
        WHERE
            TO_DATE (P.DIM_DATE, 'YYYYMMDD') <= '2023-07-31'
            AND TO_DATE (P.DIM_DATE, 'YYYYMMDD') >= '2023-03-01'
            AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
        GROUP BY
            YEAR (TO_DATE (P.DIM_DATE, 'YYYYMMDD')),
            SOUR.TXT_CATEGORY_LEVEL_2,
            S.TXT_SUPPLIER
    )
SELECT
    FMS.YEAR,
    FMS.CATEGORY,
    FMS.SUPPLIER,
    FMS.SPEND,
    LMS.PREVIOUS_SPEND,
    CASE
        WHEN LMS.PREVIOUS_SPEND > 0 THEN (
            (FMS.SPEND - LMS.PREVIOUS_SPEND) / LMS.PREVIOUS_SPEND
        ) * 100
        ELSE 0
    END AS SPEND_CHANGE_PERCENTAGE
FROM
    FIVE_MONTH_SPEND FMS
    JOIN LAST_5_MONTH_SPEND LMS ON FMS.CATEGORY = LMS.CATEGORY
    AND FMS.SUPPLIER = LMS.SUPPLIER
WHERE SPEND_CHANGE_PERCENTAGE < 100
ORDER BY
    SPEND_CHANGE_PERCENTAGE DESC