SELECT
    SUP.DIM_SUPPLIER AS SUPPLIER_ID,
    SUP.TXT_SUPPLIER AS SUPPLIER_NAME,
    COUNT(DISTINCT PT.DIM_PAYMENT_TERM) AS PAYMENT_TERM_COUNT
FROM
    DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
    JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
    JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
    JOIN DATA.VT_DIM_PAYMENTTERM PT ON PT.DIM_PAYMENT_TERM = IVP.DIM_PAYMENT_TERM
WHERE
    YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR (CURRENT_DATE)
    AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('CIBC')
GROUP BY
    SUP.DIM_SUPPLIER,
    SUP.TXT_SUPPLIER
HAVING
    COUNT(DISTINCT PT.DIM_PAYMENT_TERM) = 1