SELECT
    YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
    SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
    SUM(IVP.MES_SPEND_CURR_1) AS SPEND,
    COUNT(DISTINCT ORD.ORDER_NUMBER) AS NUMBER_OF_PURCHASE_ORDER
FROM
    DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
    JOIN DATA.VT_C_DIM_ORDERPOSITION ORD ON ORD.DIM_ORDER_POSITION = IVP.DIM_ORDER_POSITION
    JOIN DATA.VT_C_DIM_MATERIAL MAT ON IVP.DIM_MATERIAL = MAT.DIM_MATERIAL
    JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
    JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
WHERE 
    YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR (CURRENT_DATE)
    AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('CIBC')
GROUP BY
    YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
    SOUR.TXT_CATEGORY_LEVEL_2