-- Calculate the top 3 suppliers and their top 3 materials for category 'CIBC', for year 2023
WITH SUPPLIER_DATA AS (
    SELECT 
        SUP.TXT_SUPPLIER AS SUPPLIER,
        SUM(IVP.MES_SPEND_CURR_1) AS TOTAL_SPEND
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED AS IVP
        JOIN DATA.VT_DIM_PERIOD AS PER ON PER.DIM_DATE = IVP.DIM_DATE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME AS SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
        JOIN DATA.VT_C_DIM_SUPPLIER AS SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
    WHERE YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
        AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('cibc')
    GROUP BY 
            SUP.TXT_SUPPLIER
    ORDER BY TOTAL_SPEND  DESC
    LIMIT 3
),
SUPPLIER_MATERIAL_SPEND AS (
SELECT
    YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
    SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
    SUP.TXT_SUPPLIER AS SUPPLIER,
    MAT.TXT_MATERIAL AS MATERIAL,
    SUM(IVP.MES_SPEND_CURR_1) AS TOTAL_SPEND
FROM
    DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED AS IVP
    JOIN DATA.VT_DIM_PERIOD AS PER ON PER.DIM_DATE = IVP.DIM_DATE
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME AS SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
    JOIN DATA.VT_C_DIM_SUPPLIER AS SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
    JOIN DATA.VT_C_DIM_MATERIAL AS MAT ON MAT.DIM_MATERIAL = IVP.DIM_MATERIAL
WHERE
    YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
    AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('cibc')
    AND SUPPLIER IN (
        SELECT SUPPLIER FROM SUPPLIER_DATA
    )
GROUP BY
    YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
    SOUR.TXT_CATEGORY_LEVEL_2,
    SUP.TXT_SUPPLIER,
    MAT.TXT_MATERIAL
ORDER BY
    SUPPLIER ASC, MATERIAL ASC, TOTAL_SPEND DESC
),
RANKED_MATERIALS AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY YEAR, CATEGORY, SUPPLIER ORDER BY TOTAL_SPEND DESC) AS RN
    FROM SUPPLIER_MATERIAL_SPEND
)
SELECT
    YEAR,
    CATEGORY,
    SUPPLIER,
    MATERIAL,
    TOTAL_SPEND
FROM RANKED_MATERIALS
WHERE RN <= 3
ORDER BY SUPPLIER, TOTAL_SPEND DESC;