WITH PLANT_SPEND AS (
    SELECT
        YEAR(TO_DATE(PR.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        P.TXT_PLANT AS PLANT,
        SUM(FIP.MES_SPEND_CURR_1) AS SPEND
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED AS FIP
        JOIN DATA.VT_DIM_PLANT AS P ON FIP.DIM_PLANT = P.DIM_PLANT
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME AS SOUR ON SOUR.DIM_SOURCING_TREE = FIP.DIM_SOURCING_TREE
        JOIN DATA.VT_DIM_PERIOD AS PR ON FIP.DIM_DATE = PR.DIM_DATE
    WHERE
        TO_DATE(PR.DIM_DATE, 'YYYYMMDD') >= TO_DATE('20230901', 'YYYYMMDD')
        AND TO_DATE(PR.DIM_DATE, 'YYYYMMDD') <= TO_DATE('20231231', 'YYYYMMDD')
        AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
    GROUP BY
        YEAR(TO_DATE(PR.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        P.TXT_PLANT
),
LAST_QUARTER_SPEND AS (
    SELECT
        YEAR(TO_DATE(PR.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        P.TXT_PLANT AS PLANT,
        SUM(FIP.MES_SPEND_CURR_1) AS PREVIOUS_SPEND
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED AS FIP
        JOIN DATA.VT_DIM_PLANT AS P ON FIP.DIM_PLANT = P.DIM_PLANT
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME AS SOUR ON SOUR.DIM_SOURCING_TREE = FIP.DIM_SOURCING_TREE
        JOIN DATA.VT_DIM_PERIOD AS PR ON FIP.DIM_DATE = PR.DIM_DATE
    WHERE
        TO_DATE(PR.DIM_DATE, 'YYYYMMDD') >= DATEADD(MONTH, -3, TO_DATE('20230901', 'YYYYMMDD'))
        AND TO_DATE(PR.DIM_DATE, 'YYYYMMDD') < TO_DATE('20230901', 'YYYYMMDD')
        AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
    GROUP BY
        YEAR(TO_DATE(PR.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        P.TXT_PLANT
),
PLANT_SPEND_CHANGE AS (
    SELECT
        PS.YEAR,
        PS.CATEGORY,
        PS.PLANT,
        PS.SPEND,
        LQ.PREVIOUS_SPEND,
        PS.SPEND - COALESCE(LQ.PREVIOUS_SPEND, 0) AS SPEND_CHANGE,
        CASE WHEN LQ.PREVIOUS_SPEND > 0 THEN ((PS.SPEND - COALESCE(LQ.PREVIOUS_SPEND, 0))/LQ.PREVIOUS_SPEND)*100 ELSE 0 END AS SPEND_CHANGE_PERCENTAGE
    FROM
        PLANT_SPEND AS PS
        LEFT JOIN LAST_QUARTER_SPEND AS LQ ON PS.PLANT = LQ.PLANT
        AND PS.CATEGORY = LQ.CATEGORY
)
SELECT
    YEAR,
    CATEGORY,
    PLANT,
    SPEND_CHANGE,
    SPEND_CHANGE_PERCENTAGE
FROM
    PLANT_SPEND_CHANGE
WHERE SPEND_CHANGE_PERCENTAGE < 100 
AND SPEND > PREVIOUS_SPEND
ORDER BY
    SPEND_CHANGE_PERCENTAGE DESC;