SELECT
    YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
    SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
    SC.TXT_REGION AS REGION,
    SUM(MES_SPEND_CURR_1) AS SPEND
FROM
    DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED AS IVP
    JOIN DATA.VT_DIM_PERIOD AS PER ON PER.DIM_DATE = IVP.DIM_DATE
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME AS SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
    JOIN DATA.VT_DIM_SUPPLIERCOUNTRY AS SC ON SC.DIM_COUNTRY = IVP.DIM_COUNTRY
WHERE
    YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
    AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
GROUP BY
    YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
    SOUR.TXT_CATEGORY_LEVEL_2,
    SC.TXT_REGION
ORDER BY
    SPEND DESC