SELECT 
    YEAR,
    QUARTER,
    MONTH,
    CATEGORY,
    COUNTRY,
    PLANT,
    SUPPLIER,
    MATERIAL,
    MATERIAL_ID,
    INCOTERM,
    LOW_COST_SUPPLIER AS BEST_PRICE_SUPPLIER,
    SPEND AS SPEND,
    QUANTITY AS QUANTITY,
    MINIMUM_AVERAGE_PRICE AS MINIMUM_AVERAGE_PRICE,
    PRICE_AVERAGE AS PRICE_AVERAGE,
    PRICE_ARBITRAGE AS PRICE_ARBITRAGE,
    PRICE_ARBITRAGE_PERCENTAGE AS PRICE_ARBITRAGE_PERCENTAGE,
FROM 
     DATA.T_C_PRICE_ARBITRAGE
WHERE YEAR = YEAR(CURRENT_DATE)
AND QUARTER = QUARTER(CURRENT_DATE) 
AND LOWER(CATEGORY) = LOWER('Valves')
AND PRICE_ARBITRAGE > 0
ORDER BY PRICE_ARBITRAGE DESC