SELECT
    YEAR,
    CATEGORY,
    SUPPLIER,
    SUM(HCC_SPEND) AS HCC_SPEND,
    SUM(LCC_SPEND) AS LCC_SPEND,
    SUM(HCC_TO_LCC_OPPORTUNITY) AS HCC_TO_LCC_OPPORTUNITY
FROM
    DATA.T_C_HCC_LCC
WHERE YEAR = YEAR(CURRENT_DATE) AND LOWER(CATEGORY) = LOWER('Valves')
GROUP BY
    YEAR,
    CATEGORY,
    SUPPLIER
ORDER BY
    HCC_TO_LCC_OPPORTUNITY DESC