SELECT
    YEAR,
    CATEGORY,
    SUM(SPENDS) AS SPEND,
    SUM(TOTAL_OPPORTUNITY) AS TOTAL_OPPORTUNITY
FROM
    DATA.T_C_TOTAL_SAVINGS_OPPORTUNITY
WHERE YEAR = YEAR(CURRENT_DATE)
AND LOWER(CATEGORY) = LOWER('Valves')
GROUP BY 
    YEAR,
    CATEGORY
ORDER BY TOTAL_OPPORTUNITY DESC