SELECT 
    YEAR,
    CATEGORY,
    COUNT(PRICE_ARBITRAGE) AS TRANSACTION_WITH_ARBITRAGE
FROM 
    DATA.T_C_PRICE_ARBITRAGE
WHERE YEAR = YEAR(CURRENT_DATE) 
AND LOWER(CATEGORY) = LOWER('Valves')
AND PRICE_ARBITRAGE >= 0.5
GROUP BY 
    CATEGORY,
    YEAR