SELECT
    YEAR,
    CATEGORY,
    COALESCE(SUM(SPEND), 0) AS SPEND,
    COALESCE(SUM(OEM_SPEND), 0) AS OEM_SPEND,
    COALESCE(SUM(OEM_BENCHMARK_SAVING * 0.4), 0) AS OEM_NONOEM_OPPORTUNITY,
    CASE WHEN SUM(SPEND_WITH_OPPORTUNITY) > 0 THEN ROUND(SUM(OEM_SPEND)/SUM(SPEND_WITH_OPPORTUNITY),5) * 100 * 0.20 ELSE 0 END AS OEM_OPPORTUNITY_SPEND_PERCENTAGE
FROM
    DATA.T_C_OEM_NON_OEM
WHERE YEAR = YEAR(CURRENT_DATE) AND LOWER(CATEGORY) = LOWER('Valves')
GROUP BY
    YEAR,
    CATEGORY
ORDER BY
    OEM_NONOEM_OPPORTUNITY DESC