SELECT
    YEAR (TO_DATE (B.DIM_DATE, 'YYYYMMDD')) AS YEAR_,
    QUARTER (TO_DATE (B.DIM_DATE, 'YYYYMMDD')) AS QUARTER,
    SC.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
    C.TXT_MATERIAL MATERIAL,
    D.TXT_SUPPLIER,
    E.TXT_COUNTRY AS COUNTRY,
    G.TXT_PLANT AS PLANT,
    MOT.TXT_MODE_OF_TRANS AS MODE_OF_TRANS,
    ROUND(COALESCE(SUM(A.MES_SPEND_CURR_1), 0), 2) AS SPEND,
    COALESCE(SUM(A.MES_QUANTITY), 0) AS QUANTITY,
    COALESCE(COUNT(A.DIM_ORDER_POSITION), 0) AS PO_LINES_COUNT,
FROM
    DATA.VT_C_FACT_GRN_ORDERPOSITION A
    JOIN DATA.VT_DIM_PERIOD B ON B.DIM_DATE = A.DIM_DATE
    JOIN DATA.VT_C_DIM_MATERIAL C ON C.DIM_MATERIAL = A.DIM_MATERIAL
    JOIN DATA.VT_C_DIM_SUPPLIER D ON D.DIM_SUPPLIER = A.DIM_SUPPLIER
    JOIN DATA.VT_DIM_SUPPLIERCOUNTRY E ON E.DIM_COUNTRY = A.DIM_COUNTRY
    JOIN DATA.VT_DIM_INCOTERM F ON F.DIM_INCOTERM = A.DIM_INCOTERM
    JOIN DATA.VT_DIM_PLANT G ON G.DIM_PLANT = A.DIM_PLANT
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SC ON SC.DIM_SOURCING_TREE = A.DIM_SOURCING_TREE
    JOIN DATA.VT_C_DIM_ORDERDOCUMENTTYPE DT ON A.DIM_DOCUMENT_TYPE = DT.DIM_DOCUMENT_TYPE
    JOIN DATA.VT_C_DIM_MODE_OF_TRANS MOT ON A.DIM_MODE_OF_TRANS = MOT.DIM_MODE_OF_TRANS
WHERE
    G.TXT_PLANT in (
        'Emirates Aluminium Company',
        'Dubai Aluminium PJSC',
        'Al Taweelah Alumina LLC'
    )
    AND DT.DIM_DOCUMENT_TYPE in ('DSP100.F.CP', 'DSP100.F.NB', 'DSP100.F.ST')
    AND MOT.TXT_MODE_OF_TRANS = 'Air'
    AND YEAR (TO_DATE (B.DIM_DATE, 'YYYYMMDD')) = YEAR (CURRENT_DATE)
    AND QUARTER(TO_DATE (B.DIM_DATE, 'YYYYMMDD')) = QUARTER(CURRENT_DATE)
    AND LOWER(SC.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
GROUP BY
    C.TXT_MATERIAL,
    D.TXT_SUPPLIER,
    G.TXT_PLANT,
    E.TXT_COUNTRY,
    SC.TXT_CATEGORY_LEVEL_2,
    MOT.TXT_MODE_OF_TRANS,
    YEAR (TO_DATE (B.DIM_DATE, 'YYYYMMDD')),
    QUARTER (TO_DATE (B.DIM_DATE, 'YYYYMMDD'))