SELECT
    YEAR,
    CATEGORY,
    SUPPLIER,
    MATERIAL,
    SUM(SPENDS) AS SPEND,
    SUM(QUANTITY) AS QUANTITY,
    SUM(PRICE_ARBITRAGE) AS PRICE_ARBITRAGE,
    SUM(OEM_NON_OEM_OPPORTUNITY) AS OEM_NON_OEM_OPPORTUNITY,
    SUM(HCC_TO_LCC_OPPORTUNITY) AS HCC_TO_LCC_OPPORTUNITY,
    SUM(PRICE_BENCHMARK_OPPORTUNITY) AS PRICE_BENCHMARK_OPPORTUNITY,
    SUM(TOTAL_OPPORTUNITY) AS TOTAL_OPPORTUNITY
FROM
    DATA.T_C_TOTAL_SAVINGS_OPPORTUNITY
WHERE YEAR = YEAR(CURRENT_DATE)
AND LOWER(CATEGORY) = LOWER('Valves')
GROUP BY 
    YEAR,
    CATEGORY,
    SUPPLIER,
    MATERIAL
ORDER BY TOTAL_OPPORTUNITY DESC