WITH MONTHLY_SUPPLIER_TREND AS (
    SELECT
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        MONTH(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS MONTH,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        COUNT(DISTINCT GO.DIM_SUPPLIER) AS SUPPLIER_COUNT
    FROM DATA.VT_C_FACT_GRN_ORDERPOSITION GO
        JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = GO.DIM_DATE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = GO.DIM_SOURCING_TREE
        JOIN DATA.VT_C_DIM_ORDERDOCUMENTTYPE ODT ON ODT.DIM_DOCUMENT_TYPE = GO.DIM_DOCUMENT_TYPE
        JOIN DATA.VT_DIM_PLANT PL ON PL.DIM_PLANT = GO.DIM_PLANT
    WHERE
        YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
        AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
        AND PL.TXT_PLANT IN ('Al Taweelah Alumina LLC','Dubai Aluminium PJSC','Emirates Aluminium Company')
        AND ODT.DIM_DOCUMENT_TYPE IN ('DSP100.F.CP','DSP100.F.NB','DSP100.F.ST')
    GROUP BY
        YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        MONTH(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2
    ORDER BY
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        MONTH(TO_DATE (PER.DIM_DATE, 'YYYYMMDD'))
)
SELECT
    YEAR,
    MONTH,
    CATEGORY,
    SUPPLIER_COUNT AS CURRENT_SUPPLIER_COUNT,
    LAG(SUPPLIER_COUNT) OVER (PARTITION BY CATEGORY ORDER BY YEAR, MONTH) AS PREVIOUS_SUPPLIER_COUNT,
    ROUND(
        CASE
            WHEN PREVIOUS_SUPPLIER_COUNT = 0 THEN 0
            ELSE ((CURRENT_SUPPLIER_COUNT - PREVIOUS_SUPPLIER_COUNT) / PREVIOUS_SUPPLIER_COUNT) * 100
        END,
        2
    ) AS MOM_GROWTH_PERCENTAGE
FROM
    MONTHLY_SUPPLIER_TREND
ORDER BY
    YEAR,
    MONTH