WITH SPENDS_DATA AS (
SELECT
    YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
    SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
    SUM(GO.MES_SPEND_CURR_1) AS SPEND
FROM DATA.VT_C_FACT_GRN_ORDERPOSITION GO
    JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = GO.DIM_DATE
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = GO.DIM_SOURCING_TREE
    JOIN DATA.VT_C_DIM_ORDERDOCUMENTTYPE ODT ON ODT.DIM_DOCUMENT_TYPE = GO.DIM_DOCUMENT_TYPE
    JOIN DATA.VT_DIM_PLANT PL ON PL.DIM_PLANT = GO.DIM_PLANT
WHERE LOWER(TXT_CATEGORY_LEVEL_2) = LOWER('Batteries')
    AND PL.TXT_PLANT IN ('Al Taweelah Alumina LLC','Dubai Aluminium PJSC','Emirates Aluminium Company')
    AND ODT.DIM_DOCUMENT_TYPE IN ('DSP100.F.CP','DSP100.F.NB','DSP100.F.ST')
GROUP BY
    YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
    SOUR.TXT_CATEGORY_LEVEL_2
)
SELECT
    YEAR,
    CATEGORY,
    SPEND AS CURRENT_SPEND,
    LAG (SPEND) OVER (
        PARTITION BY
            CATEGORY
        ORDER BY
            YEAR
    ) AS PREVIOUS_SPEND,
    ROUND(
        CASE
            WHEN PREVIOUS_SPEND = 0 THEN 0
            ELSE ((CURRENT_SPEND - PREVIOUS_SPEND) / PREVIOUS_SPEND) * 100
        END,
        2
    ) AS YOY_GROWTH_PERCENTAGE
FROM
    SPENDS_DATA
ORDER BY
    YEAR DESC, YOY_GROWTH_PERCENTAGE DESC