WITH
    CONTRACT_DATA AS (
        SELECT
            YEAR(TO_DATE (B.DIM_DATE, 'YYYYMMDD')) AS YEAR,
            SC.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
            SUP.TXT_COUNTRY AS COUNTRY,
            CP.ORDER_NUMBER AS CONTRACT_NUMBER,
            CP.TXT_PURCHASE_GROUP AS PURCHASE_GROUP,
            D.TXT_SUPPLIER AS SUPPLIER,
            CP.DIM_CONTRACT_MATERIAL AS MATERIAL_ID,
            MAT.TXT_MATERIAL AS MATERIAL,
            CASE
                WHEN CP.DIM_CONTRACT_TYPE_NEW = 'DSP100.K.MK' THEN 'Quantity contract'
                WHEN CP.DIM_CONTRACT_TYPE_NEW = 'DSP100.K.WK' THEN 'Rate contract'
                ELSE 'Other/Undefined'
            END AS CONTRACT_TYPE,
            CP.DIM_CONTRACT_END_DATE AS CONTRACT_END_DATE,
            (TO_DATE(CP.DIM_CONTRACT_END_DATE, 'YYYYMMDD')- CURRENT_DATE) AS DAYS_UNTIL_CONTRACT_EXPIRE,
            SUM(MES_SPEND_CURR_1) AS SPEND,
            CP.MES_CONTRACT_VOLUME_NEW AS CONTRACT_VALUE,
            ROUND((CASE WHEN CP.MES_CONTRACT_VOLUME_NEW >0 THEN  SUM(MES_SPEND_CURR_1)/CP.MES_CONTRACT_VOLUME_NEW ELSE 0 END)*100,2) AS CONTRACT_UTILIZATION
        FROM
            DATA.VT_C_FACT_GRN_ORDERPOSITION A
            JOIN DATA.VT_C_DIM_CONTRACT_POSITION CP ON A.DIM_CONTRACT_POSITION = CP.DIM_CONTRACT_POSITION
            JOIN DATA.VT_DIM_PERIOD B ON B.DIM_DATE = A.DIM_DATE
            JOIN DATA.VT_C_DIM_SUPPLIER D ON D.DIM_SUPPLIER = A.DIM_SUPPLIER
            JOIN DATA.VT_C_DIM_ORDERDOCUMENTTYPE DT ON A.DIM_DOCUMENT_TYPE = DT.DIM_DOCUMENT_TYPE
            JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SC ON SC.DIM_SOURCING_TREE = A.DIM_SOURCING_TREE
            JOIN DATA.VT_DIM_SUPPLIERCOUNTRY SUP ON A.DIM_COUNTRY = SUP.DIM_COUNTRY
            JOIN DATA.VT_DIM_PLANT P ON A.DIM_PLANT = P.DIM_PLANT
            JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = A.DIM_MATERIAL
        WHERE
            P.TXT_PLANT IN (
                'Emirates Aluminium Company',
                'Dubai Aluminium PJSC',
                'Al Taweelah Alumina LLC'
            )
            AND DT.DIM_DOCUMENT_TYPE IN ('DSP100.F.CP', 'DSP100.F.NB', 'DSP100.F.ST')
            AND CP.ORDER_NUMBER <> '-1'
            AND MES_SPEND_CURR_1 > 0
            AND TO_DATE (DIM_CONTRACT_END_DATE, 'YYYYMMDD') >= CURRENT_DATE
        GROUP BY
            YEAR(TO_DATE (B.DIM_DATE, 'YYYYMMDD')),
            SC.TXT_CATEGORY_LEVEL_2,
            SUP.TXT_COUNTRY,
            CP.ORDER_NUMBER,
            CP.TXT_PURCHASE_GROUP,
            D.TXT_SUPPLIER,
            MAT.TXT_MATERIAL,
            CP.DIM_CONTRACT_MATERIAL,
            CP.DIM_CONTRACT_TYPE_NEW,
            CP.DIM_CONTRACT_END_DATE,
            CP.MES_CONTRACT_VOLUME_NEW
    )
SELECT
    YEAR,
    CATEGORY,
    COUNT(DISTINCT CONTRACT_NUMBER) AS ACTIVE_CONTRACTS
FROM
    CONTRACT_DATA
WHERE
    LOWER(CATEGORY) = LOWER('Valves')
    AND 
    YEAR = YEAR(CURRENT_DATE)
    AND LOWER(CONTRACT_TYPE) = LOWER('Quantity contract')
GROUP BY
    YEAR,
    CATEGORY
ORDER BY ACTIVE_CONTRACTS DESC