WITH CURRENT_QUARTER_DATA AS (
    SELECT
        MIN(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS MIN_DATE,
        MAX(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS MAX_DATE
    FROM
        DATA.VT_DIM_PERIOD VDP
    WHERE
        YEAR(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
        AND QUARTER(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) = QUARTER(CURRENT_DATE)
),
CURRENT_CATEGORY_DATA AS (
    SELECT
        YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS YEAR,
        QUARTER(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS QUARTER,
        TXT_COMPONENT_NAME AS COMPONENT,
        DIM_BEROE_SUBCATEGORY,
        TXT_BEROE_SUBCATEGORY AS BEROE_CATEGORY,
        AVG(MES_PRICE) AS CURRENT_COMPONENT_PRICE
    FROM
        DATA.T_C_MARKET_PRICES AS MP
    WHERE
        TO_DATE(DIM_DATE, 'YYYYMMDD') >= (
            SELECT
                MIN_DATE
            FROM
                CURRENT_QUARTER_DATA
        )
        AND TO_DATE(DIM_DATE, 'YYYYMMDD') <= (
            SELECT
                MAX_DATE
            FROM
                CURRENT_QUARTER_DATA
        )
         AND LOWER(TXT_CATEGORY) = LOWER('Bearings')
    GROUP BY
        YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')),
        QUARTER(TO_DATE(DIM_DATE, 'YYYYMMDD')),
        TXT_COMPONENT_NAME,
        DIM_BEROE_SUBCATEGORY,
        TXT_BEROE_SUBCATEGORY
),
PREVIOUS_CATEGORY_DATA AS (
  SELECT
        YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS YEAR,
        QUARTER(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS QUARTER,
        TXT_COMPONENT_NAME AS COMPONENT,
        DIM_BEROE_SUBCATEGORY,
        TXT_BEROE_SUBCATEGORY AS BEROE_CATEGORY,
        AVG(MES_PRICE) AS PREVIOUS_COMPONENT_PRICE
    FROM
        DATA.T_C_MARKET_PRICES AS MP
    WHERE
        TO_DATE(DIM_DATE, 'YYYYMMDD') >= (
            SELECT
                DATEADD(MONTH, -3, MIN_DATE)
            FROM
                CURRENT_QUARTER_DATA
        )
        AND TO_DATE(DIM_DATE, 'YYYYMMDD') <= (
            SELECT
                DATEADD(MONTH, -3, MAX_DATE)
            FROM
                CURRENT_QUARTER_DATA
        )        
        AND LOWER(TXT_CATEGORY) = LOWER('Bearings')
    GROUP BY
        YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')),
        QUARTER(TO_DATE(DIM_DATE, 'YYYYMMDD')),
        TXT_COMPONENT_NAME,
        DIM_BEROE_SUBCATEGORY,
        TXT_BEROE_SUBCATEGORY
),
CURRENT_COMPONENT_SHARE_1 AS (
    SELECT
        YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS YEAR,
        QUARTER(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS QUARTER,
        DIM_BEROE_SUBCATEGORY,
        TXT_BEROE_SUBCATEGORY AS BEROE_CATEGORY,
        TXT_COMPONENT_NAME AS COMPONENT,
        AVG(MES_SHARE_FINAL) AS COMPONENT_SHARE
    FROM
        DATA.T_C_MARKET_COST_STRUCTURE
    WHERE
        TO_DATE(DIM_DATE, 'YYYYMMDD') >= (
            SELECT
                MIN_DATE
            FROM
                CURRENT_QUARTER_DATA
        )
        AND TO_DATE(DIM_DATE, 'YYYYMMDD') <= (
            SELECT
                MAX_DATE
            FROM
                CURRENT_QUARTER_DATA
        )
         AND LOWER(TXT_CATEGORY) = LOWER('Bearings')
    GROUP BY
        YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')),
        QUARTER(TO_DATE(DIM_DATE, 'YYYYMMDD')),
        DIM_BEROE_SUBCATEGORY,
        TXT_BEROE_SUBCATEGORY,
        TXT_COMPONENT_NAME
),
CURRENT_COMPONENT_SHARE AS (
    SELECT
        CCD.YEAR,
        CCD.QUARTER,
        CCD.BEROE_CATEGORY AS CATEGORY,
        CCD.DIM_BEROE_SUBCATEGORY,
        CCD.COMPONENT,
        CURRENT_COMPONENT_PRICE,
        PREVIOUS_COMPONENT_PRICE,
        COMPONENT_SHARE,
        COALESCE(
            CURRENT_COMPONENT_PRICE / PREVIOUS_COMPONENT_PRICE,
            0
        ) -1 AS INDEX_VARIATION,
        INDEX_VARIATION * COMPONENT_SHARE AS MARKET_INFLATION
    FROM
        CURRENT_CATEGORY_DATA CCD
        JOIN PREVIOUS_CATEGORY_DATA PCD ON CCD.DIM_BEROE_SUBCATEGORY = PCD.DIM_BEROE_SUBCATEGORY
        AND CCD.BEROE_CATEGORY = PCD.BEROE_CATEGORY
        AND CCD.COMPONENT = PCD.COMPONENT
        JOIN CURRENT_COMPONENT_SHARE_1 CCS ON CCD.DIM_BEROE_SUBCATEGORY = CCS.DIM_BEROE_SUBCATEGORY
        AND CCD.BEROE_CATEGORY = CCS.BEROE_CATEGORY
        AND CCD.COMPONENT = CCS.COMPONENT
        AND CCD.YEAR = CCS.YEAR
        AND CCD.QUARTER = CCS.QUARTER
)
SELECT
    YEAR,
    QUARTER,
    CATEGORY,
    COALESCE(ROUND(SUM(MARKET_INFLATION) OVER (PARTITION BY YEAR, QUARTER, CATEGORY), 4), 0) * 100 AS TOTAL_CHANGE_IN_MARKET_PRICE_PERCENTAGE,
    COMPONENT,
    COMPONENT_SHARE,
    COALESCE(ROUND(INDEX_VARIATION,4),0) AS CHANGE_IN_COMPONENT_PRICE,
    COALESCE(ROUND(MARKET_INFLATION, 4), 0) * 100  AS COMPONENT_MARKET_INFLATION_PERCENTAGE
FROM
    CURRENT_COMPONENT_SHARE