SELECT
    YEAR,
    QUARTER,
    CATEGORY,
    SUPPLIER,
    SKU,
    CHANGE_IN_SKU_PRICE_PERCENTAGE,
    CHANGE_IN_MARKET_PRICE_PERCENTAGE
FROM
    DATA.SKU_PRICE_COMPARISON
WHERE
    YEAR = YEAR (CURRENT_DATE)
    AND QUARTER = QUARTER (CURRENT_DATE)
    AND LOWER(CATEGORY) = LOWER('Bearings')
    AND CHANGE_IN_SKU_PRICE_PERCENTAGE > CHANGE_IN_MARKET_PRICE_PERCENTAGE
ORDER BY 
    CHANGE_IN_SKU_PRICE_PERCENTAGE DESC