WITH PURCHASE_PRICE_DATA AS (
    SELECT
        YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        QUARTER (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS QUARTER,
        MONTHNAME (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS MONTH,
        ST.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        CON.TXT_COUNTRY AS COUNTRY,
        PL.TXT_PLANT AS PLANT,
        SUP.TXT_CONS_SUPPLIER_L1 AS SUPPLIER,
        MAT.TXT_MATERIAL AS MATERIAL,
        SUM(FIP.MES_SPEND_CURR_1) AS SPENDS,
        SUM(FIP.MES_QUANTITY) AS QUANTITY,
        CASE
            WHEN SUM(FIP.MES_SPEND_CURR_1) * SUM(FIP.MES_QUANTITY) > 0 THEN ABS(SUM(FIP.MES_SPEND_CURR_1)) / ABS(SUM(FIP.MES_QUANTITY))
            ELSE 0
        END AS PURCHASE_PRICE
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED FIP
        JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = FIP.DIM_DATE
        JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = FIP.DIM_MATERIAL
        JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = FIP.DIM_SUPPLIER
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME ST ON ST.DIM_SOURCING_TREE = FIP.DIM_SOURCING_TREE
        JOIN DATA.VT_DIM_SUPPLIERCOUNTRY CON ON CON.DIM_COUNTRY = FIP.DIM_COUNTRY
        JOIN DATA.VT_DIM_PLANT PL ON PL.DIM_PLANT = FIP.DIM_PLANT
    WHERE PL.TXT_PLANT <> '#' and MAT.DIM_MATERIAL <> '-1'
        AND YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
        AND LOWER(ST.TXT_CATEGORY_LEVEL_2) = LOWER('Bearings')
    GROUP BY
        YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        QUARTER (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        MONTHNAME (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        CON.TXT_COUNTRY,
        PL.TXT_PLANT,
        ST.TXT_CATEGORY_LEVEL_2,
        MAT.TXT_MATERIAL,
        SUP.TXT_CONS_SUPPLIER_L1
),
SHOULD_COST_PRE AS (
    SELECT
        YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        QUARTER (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS QUARTER,
        MONTHNAME (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS MONTH,
        ST.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        MAT.TXT_MATERIAL AS MATERIAL,
        COMP.TXT_COMPONENT AS COMPONENT,
        AVG(FIS.MES_SHOULD_COST) AS SHOULD_COST
    FROM
        DATA.VT_FACT_ICM_SHOULDCOST FIS
        JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = FIS.DIM_DATE
        JOIN DATA.VT_DIM_ICM_ARCHETYPE_INDEX_MAPPING IAIM ON IAIM.DIM_COMBINATION_KEY = FIS.DIM_COMBINATION_KEY
        JOIN DATA.VT_DIM_ICM_COMPONENT COMP ON COMP.DIM_COMPONENT_KEY = IAIM.DIM_COMPONENT_KEY
        JOIN DATA.VT_DIM_ICM_MAPPING ICM ON ICM.DIM_ARCHETYPE = IAIM.DIM_ARCHETYPE
        JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = ICM.DIM_MATERIAL
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME ST ON ST.DIM_SOURCING_TREE = ICM.DIM_SOURCING_TREE
    WHERE
        YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
        AND LOWER(ST.TXT_CATEGORY_LEVEL_2) = LOWER('Bearings')
    GROUP BY
        YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        QUARTER (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        MONTHNAME (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        ST.TXT_CATEGORY_LEVEL_2,
        MAT.TXT_MATERIAL,
        COMP.TXT_COMPONENT
),
SHOULD_COST_DATA AS (
    SELECT
        YEAR,
        QUARTER,
        MONTH,
        CATEGORY,
        MATERIAL,
        SUM(SHOULD_COST) AS SHOULD_COST
    FROM 
        SHOULD_COST_PRE
    GROUP BY 
        YEAR,
        QUARTER,
        MONTH,
        CATEGORY,
        MATERIAL
),
CLEANSHEET_DATA AS (
    SELECT
        PPD.YEAR,
        PPD.QUARTER,
        PPD.MONTH,
        PPD.CATEGORY,
        PPD.PLANT,
        PPD.COUNTRY,
        PPD.MATERIAL,
        PPD.SUPPLIER,
        SUM(SPENDS) AS SPENDS,
        SUM(PPD.PURCHASE_PRICE),
        SUM(SCD.SHOULD_COST),
        SUM(PPD.PURCHASE_PRICE)-SUM(SCD.SHOULD_COST),
        SUM(PPD.QUANTITY),
        (SUM(PPD.PURCHASE_PRICE) - SUM(SCD.SHOULD_COST)) * SUM(PPD.QUANTITY) AS PARAMETER_COST_MODELLING_OPPORTUNITY
    FROM
        PURCHASE_PRICE_DATA PPD
        JOIN SHOULD_COST_DATA SCD ON PPD.YEAR = SCD.YEAR
        AND PPD.MATERIAL = SCD.MATERIAL 
        AND PPD.QUARTER = SCD.QUARTER AND PPD.MONTH = SCD.MONTH
        AND PPD.CATEGORY = SCD.CATEGORY
    GROUP BY
        PPD.YEAR,
        PPD.QUARTER,
        PPD.MONTH,
        PPD.PLANT,
        PPD.COUNTRY,
        PPD.CATEGORY,
        PPD.MATERIAL,
        PPD.SUPPLIER
)
    SELECT
        YEAR,
        QUARTER,
        MONTH,
        CATEGORY,
        MATERIAL,
        SUPPLIER,
        PLANT,
        COUNTRY,
        SPENDS AS SPEND,
        PARAMETER_COST_MODELLING_OPPORTUNITY,
        CONCAT(ROUND(DIV0(PARAMETER_COST_MODELLING_OPPORTUNITY * 100, SPENDS),2), '%') AS SPEND_SAVINGS_PERCENTAGE
    FROM
        CLEANSHEET_DATA
    ORDER BY
        YEAR DESC,
        QUARTER DESC,
        MONTH ASC,
        CATEGORY DESC