WITH DISCOUNTSUMMARY AS (
   SELECT
        YEAR(TO_DATE(P.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        ST.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        S.TXT_CONS_SUPPLIER_L1,
        SC.TXT_COUNTRY,
        G.TXT_PLANT,
        F.TXT_INCOTERM_ABB,
        PT.TXT_CONS_PAYMENT_TERM AS PAYMENT_TERM_GROUP,
        C.TXT_MATERIAL,
        SUM(FP.MES_SPEND_PAID_CURR_1) AS SPEND,
        SUM(FP.MES_DISCOUNT_POSSIBLE_CURR_1) AS DISCOUNT_POSSIBLE,
        SUM(FP.MES_DISCOUNT_CURR_1) AS DISCOUNT
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_PAYMENT FP
        LEFT OUTER JOIN DATA.VT_DIM_PAYMENTTERM AS PT ON FP.DIM_PAYMENT_TERM = PT.DIM_PAYMENT_TERM
        LEFT OUTER JOIN DATA.VT_C_DIM_VALUETYPE AS VT ON FP.DIM_VALUE_TYPE = VT.DIM_VALUE_TYPE
        LEFT OUTER JOIN DATA.VT_C_DIM_SUPPLIER AS S ON FP.DIM_SUPPLIER = S.DIM_SUPPLIER
        LEFT OUTER JOIN DATA.VT_C_DIM_MATERIAL C ON FP.DIM_MATERIAL = C.DIM_MATERIAL
        LEFT OUTER JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME ST ON FP.DIM_SOURCING_TREE = ST.DIM_SOURCING_TREE
        LEFT OUTER JOIN DATA.VT_DIM_PERIOD P ON FP.DIM_DATE = P.DIM_DATE
        LEFT OUTER JOIN DATA.VT_DIM_SUPPLIERCOUNTRY SC ON FP.DIM_COUNTRY=SC.DIM_COUNTRY 
        LEFT OUTER JOIN DATA.VT_DIM_INCOTERM F ON FP.DIM_INCOTERM = F.DIM_INCOTERM
        LEFT OUTER JOIN DATA.VT_DIM_PLANT G ON FP.DIM_PLANT = G.DIM_PLANT
    WHERE VT.DIM_VALUE_TYPE = 'P' AND 
    LOWER(PT.TXT_PAYMENT_TERM_TYPE) = LOWER('Discount')
    AND G.DIM_PLANT !='-1' AND FP.DIM_MATERIAL!='-1'
    AND YEAR(TO_DATE(P.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE) AND LOWER(ST.TXT_CATEGORY_LEVEL_2) = LOWER('Bearings')
    GROUP BY
        YEAR(TO_DATE(P.DIM_DATE, 'YYYYMMDD')),
        S.TXT_CONS_SUPPLIER_L1,
        ST.TXT_CATEGORY_LEVEL_2,
        C.TXT_MATERIAL,
        PT.TXT_CONS_PAYMENT_TERM,
        F.TXT_INCOTERM_ABB,
        SC.TXT_COUNTRY,
        G.TXT_PLANT
)
SELECT
    YEAR,
    CATEGORY,
    DS.TXT_CONS_SUPPLIER_L1 AS SUPPLIER,
    DS.TXT_COUNTRY,
    ROUND(DS.DISCOUNT_POSSIBLE, 2) AS DISCOUNT_POSSIBLE,
    ROUND(DS.DISCOUNT, 2) AS DISCOUNT,
    ROUND(CASE
        WHEN (DS.DISCOUNT_POSSIBLE - DS.DISCOUNT) < 0
        THEN 0
        ELSE (DS.DISCOUNT_POSSIBLE - DS.DISCOUNT)
    END, 2) AS DISCOUNT_NOT_USED
FROM
    DISCOUNTSUMMARY DS
WHERE LOWER(DS.TXT_COUNTRY) = LOWER('Germany')