WITH BASE_TABLE AS (
    SELECT
    MAT.DIM_MATERIAL AS MATERIAL
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED AS IVP
        JOIN DATA.VT_DIM_PERIOD AS PER ON PER.DIM_DATE = IVP.DIM_DATE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME AS SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
        JOIN DATA.VT_C_DIM_MATERIAL AS MAT ON MAT.DIM_MATERIAL = IVP.DIM_MATERIAL
    WHERE
        YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = 2023
        AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('CIBC')
    GROUP BY
        MAT.DIM_MATERIAL
    HAVING
        SUM(IVP.MES_SPEND_CURR_1) > 100000
)
SELECT COUNT(DISTINCT MATERIAL) AS COUNT_OF_MATERIALS
FROM BASE_TABLE