WITH
    AVERAGE_PRICE_DATA AS (
        SELECT
            YEAR (
                TO_DATE(PER.DIM_DATE, 'YYYYMMDD')
            ) AS YEAR,
            SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
            SC.TXT_COUNTRY AS COUNTRY,
            SC.TXT_CONTINENT AS CONTINENT,
            SUM(MES_SPEND_CURR_1) AS SPEND,
            SUM(MES_QUANTITY) AS QUANTITY,
        FROM
            DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED AS IVP
            JOIN DATA.VT_DIM_PERIOD AS PER ON PER.DIM_DATE = IVP.DIM_DATE
            JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME AS SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
            JOIN DATA.VT_DIM_SUPPLIERCOUNTRY AS SC ON SC.DIM_COUNTRY = IVP.DIM_COUNTRY
        WHERE
            YEAR (
                TO_DATE(PER.DIM_DATE, 'YYYYMMDD')
            ) = YEAR (CURRENT_DATE)
            AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('CIBC')
            AND LOWER(SC.TXT_CONTINENT) = LOWER('Europe')
        GROUP BY
            YEAR (
                TO_DATE(PER.DIM_DATE, 'YYYYMMDD')
            ),
            SOUR.TXT_CATEGORY_LEVEL_2,
            SC.TXT_COUNTRY,
            SC.TXT_CONTINENT
    )
SELECT
    YEAR,
    CATEGORY,
    CONTINENT,
    COUNTRY,
    CASE
        WHEN QUANTITY > 0 THEN SPEND / QUANTITY
        ELSE 0
    END AS AVERAGE_PRICE
FROM AVERAGE_PRICE_DATA
ORDER BY AVERAGE_PRICE DESC