WITH SPENDS_DATA AS (
SELECT
    YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
    SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
    TXT_SUPPLIER AS SUPPLIER,
    SUM(IVP.MES_SPEND_CURR_1) AS SPEND
FROM
    DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
    JOIN DATA.VT_C_DIM_MATERIAL MAT ON IVP.DIM_MATERIAL = MAT.DIM_MATERIAL
    JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
    JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
WHERE 
    LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
    AND YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) IN (YEAR(CURRENT_DATE), YEAR(CURRENT_DATE)-1)
GROUP BY
    YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
    SOUR.TXT_CATEGORY_LEVEL_2,
    TXT_SUPPLIER
)
SELECT
    YEAR,
    CATEGORY,
    SUPPLIER,
    SPEND AS CURRENT_SPEND,
    COALESCE(LAG (SPEND) OVER (
        PARTITION BY
            CATEGORY, SUPPLIER
        ORDER BY
            YEAR
    ),0) AS PREVIOUS_SPEND,
    ROUND(
        CASE
            WHEN PREVIOUS_SPEND = 0 THEN 0
            ELSE (CURRENT_SPEND - PREVIOUS_SPEND)
        END,
        2
    ) AS YOY_SPEND_CHANGE
FROM
    SPENDS_DATA
ORDER BY
    YEAR DESC, YOY_SPEND_CHANGE DESC