SELECT 
    YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
    SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
    SUP.DIM_SUPPLIER AS SUPPLIER_ID,
    SUP.TXT_SUPPLIER AS SUPPLIER_NAME,
    COUNT(DISTINCT MAT.DIM_MATERIAL) AS MATERIAL_COUNT
FROM DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = IVP.DIM_MATERIAL
WHERE YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
    AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('CIBC')
    AND MAT.DIM_MATERIAL != '-1'
GROUP BY 
    YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
    SOUR.TXT_CATEGORY_LEVEL_2,
    SUP.DIM_SUPPLIER,
    SUP.TXT_SUPPLIER
ORDER BY COUNT(DISTINCT MAT.DIM_MATERIAL) DESC