WITH OPERATING_DATA AS (
    SELECT
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SUP.TXT_SUPPLIER AS SUPPLIER,
        COUNT(DISTINCT COMP.TXT_LEVEL_4) AS OPERATING_UNITS_COUNT,
        SUM(MES_SPEND_CURR_1) AS TOTAL_SPEND
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
        JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
        JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
        JOIN DATA.VT_DIM_COMPANY COMP ON COMP.DIM_COMPANY = IVP.DIM_COMPANY
    WHERE
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
         AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
         AND COMP.TXT_LEVEL_4 != '-1'
    GROUP BY 
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        SUP.TXT_SUPPLIER
)
SELECT 
    YEAR,
    CATEGORY,
    SUM(OPERATING_UNITS_COUNT) AS TOTAL_OPERATING_UNITS,
    ROUND(SUM(TOTAL_SPEND),2) AS TOTAL_SPEND,
    SUM(CASE WHEN OPERATING_UNITS_COUNT = 1 THEN OPERATING_UNITS_COUNT ELSE 0 END) AS SINGLE_OPERATING_UNITS_COUNT,
    ROUND(SUM(CASE WHEN OPERATING_UNITS_COUNT = 1 THEN TOTAL_SPEND ELSE 0 END),2) AS SINGLE_OPERATING_UNITS_SPEND,
    SUM(CASE WHEN OPERATING_UNITS_COUNT > 1 THEN OPERATING_UNITS_COUNT ELSE 0 END) AS MULTI_OPERATING_UNITS_COUNT,
    ROUND(SUM(CASE WHEN OPERATING_UNITS_COUNT > 1 THEN TOTAL_SPEND ELSE 0 END),2) AS MULTI_OPERATING_UNITS_SPEND
FROM OPERATING_DATA
GROUP BY YEAR,
    CATEGORY
ORDER BY TOTAL_SPEND DESC;