SELECT
    YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
    QUARTER (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS QUARTER,
    SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
    IVP.DIM_CONTRACT_REFERENCE,
    CR.TXT_CONTRACTREFERENCE,
    SUM(MES_SPEND_CURR_1) AS TOTAL_SPEND
FROM
    DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
    JOIN DATA.VT_DIM_CONTRACTREFERENCE CR ON CR.DIM_CONTRACTREFERENCE = IVP.DIM_CONTRACT_REFERENCE
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME_ORIGINAL SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
    JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
WHERE
    YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR (CURRENT_DATE)
    AND QUARTER (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = QUARTER (CURRENT_DATE)
    AND SOUR.TXT_CATEGORY_LEVEL_2 = 'Bearings'
GROUP BY
    YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
    QUARTER (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
    TXT_CATEGORY_LEVEL_2,
    IVP.DIM_CONTRACT_REFERENCE,
    CR.TXT_CONTRACTREFERENCE