WITH SKUData AS (
SELECT
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) AS Year,
	ct.TXT_CATEGORY_LEVEL_2 AS Category,
	s.TXT_CONS_SUPPLIER_L1 AS Supplier,
	m.TXT_Material AS SKU,
	COUNT(fip.DIM_MATERIAL) AS SKU_Count
FROM
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED fip
JOIN 
        data.VT_DIM_Period p ON
	p.DIM_DATE = fip.DIM_DATE
JOIN 
        data.VT_C_DIM_Supplier s ON
	s.DIM_SUPPLIER = fip.DIM_SUPPLIER
JOIN 
        data.VT_DIM_SupplierStatus ss ON
	ss.DIM_SUPPLIER_STATUS = fip.DIM_SUPPLIER_STATUS
JOIN 
        data.VT_C_DIM_ValueType vt ON
	vt.dim_value_type = fip.DIM_VALUE_TYPE
JOIN 
        data.VT_C_DIM_Material m ON
	m.DIM_MATERIAL = fip.DIM_MATERIAL
JOIN 
        data.VT_C_DIM_SourcingTree_TECHCME ct ON
	ct.DIM_SOURCING_TREE = fip.DIM_SOURCING_TREE
WHERE
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_TIMESTAMP)
	AND lower(s.TXT_CONS_SUPPLIER_L1) = lower('SKF FRANCE')
	AND ss.DIM_SUPPLIER_STATUS = 'E'
	AND vt.DIM_VALUE_TYPE = 'I'
	AND ct.TXT_CATEGORY_LEVEL_2 = 'Bearings'
GROUP BY
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')),
	ct.TXT_CATEGORY_LEVEL_2,
	s.TXT_CONS_SUPPLIER_L1,
	m.TXT_Material
)
SELECT
	Year,
	Category,
	Supplier,
	SKU,
	SKU_Count
FROM
	SKUData
ORDER BY
	SKU_Count DESC