SELECT
    YEAR,
    CATEGORY,
    SUPPLIER,
    SUM(PRICE_ARBITRAGE) AS PRICE_ARBITRAGE,
    AVG(PRICE_ARBITRAGE_PERCENTAGE) AS PRICE_ARBITRAGE_PERCENTAGE
FROM DATA.T_C_PRICE_ARBITRAGE
WHERE YEAR = YEAR(CURRENT_DATE)
AND LOWER(CATEGORY) = LOWER('Valves')
GROUP BY 
    YEAR,
    CATEGORY,
    SUPPLIER
ORDER BY PRICE_ARBITRAGE DESC