WITH SUPPLIERS_NO AS (
    SELECT
        YEAR,
        CATEGORY,
        SUPPLIER,
        MATERIAL,
        MATERIAL_ID,
        SUM(LPP_CORRUGATES_OPPORTUNITY) AS LPP_CORRUGATES_OPPORTUNITY
    FROM
        DATA.T_C_LPP
    WHERE
        YEAR = YEAR(CURRENT_DATE)
        AND LOWER(CATEGORY) = LOWER('CIBC')
    GROUP BY
        YEAR,
        CATEGORY,
        SUPPLIER,
        MATERIAL_ID,
        MATERIAL
    HAVING
        SUM(LPP_CORRUGATES_OPPORTUNITY) > 0 AND SUM(LPP_CORRUGATES_OPPORTUNITY) < 1
),
SUPPLIER_OPP AS (
    SELECT
        YEAR,
        CATEGORY,
        SUPPLIER,
        MATERIAL_ID,
        MATERIAL,
        SUM(LPP_CORRUGATES_OPPORTUNITY) AS LPP_CORRUGATES_OPPORTUNITY
    FROM
        DATA.T_C_LPP
    WHERE
        YEAR = YEAR(CURRENT_DATE)
        AND LOWER(CATEGORY) = LOWER('CIBC')
    GROUP BY
        YEAR,
        CATEGORY,
        SUPPLIER,
        MATERIAL_ID,
        MATERIAL
    HAVING
        SUM(LPP_CORRUGATES_OPPORTUNITY) > 1
    ORDER BY
        LPP_CORRUGATES_OPPORTUNITY DESC
)
SELECT
    SO.YEAR,
    SO.CATEGORY,
    SO.SUPPLIER,
    SO.MATERIAL,
    SO.MATERIAL_ID,
    SO.LPP_CORRUGATES_OPPORTUNITY,
    SN.SUPPLIER AS SUPPLIER_LPP,
    SN.MATERIAL AS MATERIAL_LPP,
    SN.LPP_CORRUGATES_OPPORTUNITY AS LPP_CORRUGATES_OPPORTUNITY_LPP
FROM
    SUPPLIER_OPP SO
    JOIN SUPPLIERS_NO SN 
    ON SN.YEAR = SO.YEAR
    AND SO.CATEGORY = SN.CATEGORY
    AND SO.MATERIAL = SN.MATERIAL
    AND SO.MATERIAL_ID = SN.MATERIAL_ID
ORDER BY LPP_CORRUGATES_OPPORTUNITY DESC
LIMIT 1