WITH SPEND_DATA AS (
    SELECT 
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SUP.TXT_SUPPLIER AS SUPPLIER,
        MAT.TXT_MATERIAL AS MATERIAL,
        SUM(IVP.MES_SPEND_CURR_1) AS SPEND,
        SUM(IVP.MES_QUANTITY) AS QUANTITY,
    FROM DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
    JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
    JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
    JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = IVP.DIM_MATERIAL
    JOIN DATA.VT_DIM_SUPPLIERCOUNTRY SC ON SC.DIM_COUNTRY = IVP.DIM_COUNTRY
    JOIN DATA.VT_DIM_PLANT PT ON PT.DIM_PLANT = IVP.DIM_PLANT
    WHERE YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) =  YEAR(CURRENT_DATE)
    AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('CIBC')
    GROUP BY
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        SUP.TXT_SUPPLIER,
        MAT.TXT_MATERIAL
),
PRICE_ARBITRAGE_DATA AS (
SELECT YEAR, CATEGORY, SUPPLIER, MATERIAL, SUM(PRICE_ARBITRAGE) AS PRICE_ARBITRAGE FROM DATA.T_C_PRICE_ARBITRAGE
WHERE YEAR =  YEAR(CURRENT_DATE) AND LOWER(CATEGORY) =  LOWER('CIBC')
GROUP BY YEAR, CATEGORY, SUPPLIER, MATERIAL
),
PCM_DATA AS (
SELECT YEAR, CATEGORY, MATERIAL, SUPPLIER, SUM(CLEANSHEET_OPPORTUNITY) AS CLEANSHEET_OPPORTUNITY FROM DATA.T_C_PARAMETRIC_COST_MODELLING
WHERE YEAR =  YEAR(CURRENT_DATE) AND LOWER(CATEGORY) =  LOWER('CIBC')
GROUP BY YEAR, CATEGORY, SUPPLIER, MATERIAL
),
LPP_DATA AS (
SELECT YEAR, CATEGORY, SUPPLIER, MATERIAL, SUM(LPP_CORRUGATES_OPPORTUNITY) AS LPP_CORRUGATES_OPPORTUNITY FROM DATA.T_C_LPP
WHERE YEAR =  YEAR(CURRENT_DATE) AND LOWER(CATEGORY) =  LOWER('CIBC')
GROUP BY YEAR, CATEGORY, SUPPLIER, MATERIAL
)
SELECT 
    SD.YEAR,
    SD.CATEGORY,
    SD.MATERIAL,
    SUM(GREATEST(COALESCE(PD.PRICE_ARBITRAGE, 0),COALESCE(PC.CLEANSHEET_OPPORTUNITY,0), COALESCE(LP.LPP_CORRUGATES_OPPORTUNITY,0))) AS TOTAL_OPPORTUNITY
FROM SPEND_DATA SD
LEFT JOIN PRICE_ARBITRAGE_DATA PD ON SD.YEAR = PD.YEAR AND SD.CATEGORY = PD.CATEGORY AND SD.SUPPLIER = PD.SUPPLIER AND SD.MATERIAL = PD.MATERIAL
LEFT JOIN PCM_DATA PC ON SD.YEAR = PC.YEAR AND SD.CATEGORY = PC.CATEGORY AND SD.SUPPLIER = PC.SUPPLIER AND SD.MATERIAL = PC.MATERIAL
LEFT JOIN LPP_DATA LP ON SD.YEAR = LP.YEAR AND SD.CATEGORY = LP.CATEGORY AND SD.SUPPLIER = LP.SUPPLIER AND SD.MATERIAL = LP.MATERIAL
GROUP BY 
    SD.YEAR,
    SD.CATEGORY,
    SD.MATERIAL
ORDER BY TOTAL_OPPORTUNITY DESC