SELECT
    YEAR,
    CATEGORY,
    COUNTRY,
    PLANT,
    SUPPLIER,
    MATERIAL,
    INCOTERM,
    SUM(SPEND) AS SPEND,
    SUM(QUANTITY) AS QUANTITY,
    AVG(MINIMUM_AVERAGE_PRICE) AS MINIMUM_AVERAGE_PRICE,
    AVG(PRICE_AVERAGE) AS PRICE_AVERAGE,
    SUM(PRICE_ARBITRAGE) AS PRICE_ARBITRAGE,
    AVG(PRICE_ARBITRAGE_PERCENTAGE) AS PRICE_ARBITRAGE_PERCENTAGE
FROM
    DATA.T_C_PRICE_ARBITRAGE
WHERE 
    YEAR = YEAR(CURRENT_DATE)
AND LOWER(CATEGORY) = LOWER('CIBC')
GROUP BY 
    YEAR,
    CATEGORY,
    COUNTRY,
    PLANT,
    SUPPLIER,
    MATERIAL,
    INCOTERM