SELECT
    YEAR,
    CATEGORY,
    COUNTRY,
    SUPPLIER,
    MATERIAL,
    SUM(LPP_CORRUGATES_OPPORTUNITY) AS LPP_CORRUGATES_OPPORTUNITY
FROM DATA.T_C_LPP
WHERE
    LOWER(CATEGORY) = LOWER('CIBC')
    AND YEAR = YEAR (CURRENT_DATE)
GROUP BY 
    YEAR,
    CATEGORY,
    COUNTRY,
    SUPPLIER,
    MATERIAL
ORDER BY LPP_CORRUGATES_OPPORTUNITY DESC