SELECT
    YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')) AS YEAR,
    TXT_CATEGORY AS CATEGORY,
    TXT_BEROE_SUBCATEGORY AS BEROE_CATEGORY,
    TXT_COMPONENT_NAME AS COMPONENT,
    ROUND(AVG(MES_SHARE_FINAL), 2) AS COMPONENT_SHARE,
    CONCAT(ROUND(AVG(MES_SHARE_FINAL) * 100, 2), '%') AS COMPONENT_SHARE_PERCENT
FROM
    DATA.T_C_MARKET_COST_STRUCTURE
WHERE
    YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
    AND LOWER(TXT_CATEGORY) = LOWER('Bearings')
GROUP BY
    YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')),
    TXT_CATEGORY,
    TXT_BEROE_SUBCATEGORY,
    TXT_COMPONENT_NAME
ORDER BY COMPONENT_SHARE DESC