WITH
    CURRENT_QUARTER_DATA AS (
        SELECT
            MIN(TO_DATE (DIM_DATE, 'YYYYMMDD')) AS MIN_DATE,
            MAX(TO_DATE (DIM_DATE, 'YYYYMMDD')) AS MAX_DATE
        FROM
            DATA.VT_DIM_PERIOD VDP
        WHERE
            YEAR (TO_DATE (VDP.DIM_DATE, 'YYYYMMDD')) = YEAR (CURRENT_DATE)
            AND QUARTER (TO_DATE (VDP.DIM_DATE, 'YYYYMMDD')) = QUARTER (CURRENT_DATE)
    ),
    SELECTED_QUARTER_DATA AS (
        SELECT
            YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')) AS YEAR,
            QUARTER (TO_DATE (DIM_DATE, 'YYYYMMDD')) AS QUARTER,
            TXT_CATEGORY AS CATEGORY,
            TXT_BEROE_SUBCATEGORY AS BEROE_CATEGORY,
            TXT_COMPONENT_NAME AS COMPONENT,
            AVG(MES_PRICE) AS PRICE
        FROM
            DATA.T_C_MARKET_PRICES
        WHERE
            TO_DATE (DIM_DATE, 'YYYYMMDD') >= (
                SELECT
                    MIN_DATE
                FROM
                    CURRENT_QUARTER_DATA
            )
            AND TO_DATE (DIM_DATE, 'YYYYMMDD') <= (
                SELECT
                    MAX_DATE
                FROM
                    CURRENT_QUARTER_DATA
            )
            AND LOWER(TXT_CATEGORY) = LOWER('Bearings')
        GROUP BY
            YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')),
            QUARTER (TO_DATE (DIM_DATE, 'YYYYMMDD')),
            TXT_CATEGORY,
            TXT_BEROE_SUBCATEGORY,
            TXT_COMPONENT_NAME
    ),
    NEXT_12_MONTHS_QUARTER_DATA AS (
        SELECT
            YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')) AS YEAR,
            QUARTER (TO_DATE (DIM_DATE, 'YYYYMMDD')) AS QUARTER,
            TXT_CATEGORY AS CATEGORY,
            TXT_BEROE_SUBCATEGORY AS BEROE_CATEGORY,
            TXT_COMPONENT_NAME AS COMPONENT,
            AVG(MES_PRICE) AS NEXT_PRICE
        FROM
            DATA.T_C_MARKET_PRICES
        WHERE
            TO_DATE (DIM_DATE, 'YYYYMMDD') >= (
                SELECT
                    DATEADD (MONTH, 12, MIN_DATE)
                FROM
                    CURRENT_QUARTER_DATA
            )
            AND TO_DATE (DIM_DATE, 'YYYYMMDD') <= (
                SELECT
                    DATEADD (MONTH, 12, MAX_DATE)
                FROM
                    CURRENT_QUARTER_DATA
            )
            AND LOWER(TXT_CATEGORY) = LOWER('Bearings')
        GROUP BY
            YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')),
            QUARTER (TO_DATE (DIM_DATE, 'YYYYMMDD')),
            TXT_CATEGORY,
            TXT_BEROE_SUBCATEGORY,
            TXT_COMPONENT_NAME
    ),
    COMPONENT_SHARE_DATA AS (
        SELECT
            YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')) AS YEAR,
            QUARTER (TO_DATE (DIM_DATE, 'YYYYMMDD')) AS QUARTER,
            TXT_CATEGORY AS CATEGORY,
            TXT_BEROE_SUBCATEGORY AS BEROE_CATEGORY,
            TXT_COMPONENT_NAME AS COMPONENT,
            AVG(MES_SHARE_FINAL) AS COMPONENT_SHARE
        FROM
            DATA.T_C_MARKET_COST_STRUCTURE
        WHERE
            TO_DATE (DIM_DATE, 'YYYYMMDD') >= (
                SELECT
                    MIN_DATE
                FROM
                    CURRENT_QUARTER_DATA
            )
            AND TO_DATE (DIM_DATE, 'YYYYMMDD') <= (
                SELECT
                    MAX_DATE
                FROM
                    CURRENT_QUARTER_DATA
            )
            AND LOWER(TXT_CATEGORY) = LOWER('Bearings')
        GROUP BY
            YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')),
            QUARTER (TO_DATE (DIM_DATE, 'YYYYMMDD')),
            TXT_CATEGORY,
            TXT_BEROE_SUBCATEGORY,
            TXT_COMPONENT_NAME
    ),
	FORECAST_12_MONTH_DATA AS (
		SELECT
            SQD.YEAR,
            SQD.QUARTER,
            SQD.COMPONENT AS COMPONENT,
            ROUND(PRICE, 2) AS CURRENT_QUARTER_PRICE,
            NMD.YEAR AS NEXT_YEAR,
            NMD.QUARTER AS NEXT_QUARTER,
			ROUND(NEXT_PRICE, 2) AS NEXT_12_MONTH_QUARTER_PRICE,
			ROUND(
				(((NEXT_PRICE - PRICE) / PRICE) * COMPONENT_SHARE) * 100,
				2
			) AS NEXT_12_MONTH_COMPONENT_FORECAST,
			CONCAT (
				ROUND(
					(((NEXT_PRICE - PRICE) / PRICE) * COMPONENT_SHARE) * 100,
					2
				),
				'%'
			) AS NEXT_12_MONTH_COMPONENT_FORECAST_PERCENTAGE
		FROM
            SELECTED_QUARTER_DATA SQD
        JOIN NEXT_12_MONTHS_QUARTER_DATA NMD ON SQD.COMPONENT = NMD.COMPONENT
            AND SQD.BEROE_CATEGORY = NMD.BEROE_CATEGORY
            AND SQD.CATEGORY = NMD.CATEGORY
        JOIN COMPONENT_SHARE_DATA CSD ON CSD.YEAR = SQD.YEAR
            AND CSD.QUARTER = SQD.QUARTER
            AND CSD.COMPONENT = SQD.COMPONENT
            AND CSD.BEROE_CATEGORY = SQD.BEROE_CATEGORY
            AND CSD.CATEGORY = SQD.CATEGORY
	)
SELECT
	MAX(YEAR) AS YEAR,
    MAX(QUARTER) AS QUARTER,
	SUM(CURRENT_QUARTER_PRICE) AS CURRENT_QUARTER_PRICE,
	MAX(YEAR) AS FORECASTED_YEAR,
    MAX(QUARTER) AS FORECASTED_QUARTER,
	SUM(NEXT_12_MONTH_QUARTER_PRICE) AS NEXT_12_MONTH_QUARTER_PRICE,
	SUM(NEXT_12_MONTH_COMPONENT_FORECAST) AS NEXT_12_MONTH_COMPONENT_FORECAST,
	ROUND(SUM(NEXT_12_MONTH_COMPONENT_FORECAST), 2) AS NEXT_12_MONTH_COMPONENT_FORECAST_PERCENTAGE
FROM
	FORECAST_12_MONTH_DATA