SELECT
    PARENT_SUPPLIER_NAME,
    SUPPLIER_NAME,
    CATEGORY,
    CHANNEL,
    INDUSTRY_NAME,
    TOPIC_NAME,
    TITLE,
    DESCRIPTION,
    URL,
    PUBLISHED_DATE
FROM
    DATA.SUPPLIER_NEWS
WHERE LOWER(CATEGORY) = LOWER('Bearings')
AND LOWER(PARENT_SUPPLIER_NAME) LIKE LOWER('SKF France')
ORDER BY PUBLISHED_DATE DESC;