SELECT
    YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
    SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
    SUP.TXT_CONS_SUPPLIER_L1 AS SUPPLIER,
    COUNT(DISTINCT COMP.TXT_LEVEL_4) AS MULTI_OPERATING_UNITS_COUNT,
    SUM(MES_SPEND_CURR_1) AS TOTAL_SPEND
FROM
    DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
    JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
    JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
    JOIN DATA.VT_DIM_COMPANY COMP ON COMP.DIM_COMPANY = IVP.DIM_COMPANY
WHERE
    YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
     AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Marketing Svcs')
     AND COMP.TXT_LEVEL_4 != '-1'
GROUP BY
    YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
    SOUR.TXT_CATEGORY_LEVEL_2,
    SUP.TXT_CONS_SUPPLIER_L1
HAVING COUNT(DISTINCT COMP.TXT_LEVEL_4) > 1
ORDER BY TOTAL_SPEND DESC