WITH BASE_TABLE AS (
    SELECT
        YEAR(TO_DATE(B.DIM_DATE, 'YYYYMMDD')) AS YEAR_,
        QUARTER(TO_DATE(B.DIM_DATE, 'YYYYMMDD')) AS QUARTER,    
        MONTHNAME(TO_DATE(B.DIM_DATE, 'YYYYMMDD')) AS MONTH,       
        C.TXT_MATERIAL AS TXT_MATERIAL,
        A.DIM_MATERIAL AS DIM_MATERIAL,
        A.DIM_SUPPLIER,
        D.TXT_CONS_SUPPLIER_L1,
        E.TXT_COUNTRY,
        A.DIM_COUNTRY,
        F.TXT_INCOTERM,
        A.DIM_INCOTERM,
        A.DIM_PLANT,
        G.TXT_PLANT,
        SC.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SUM(A.MES_SPEND_CURR_1) AS SPEND,
        SUM(A.MES_QUANTITY) AS QUANTITY,
        CASE
            WHEN SUM(A.MES_QUANTITY) > 0 THEN SUM(A.MES_SPEND_CURR_1) / SUM(A.MES_QUANTITY)
            ELSE 0
        END AS PRICE_AVG
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED A
        JOIN DATA.VT_DIM_PERIOD B ON A.DIM_DATE = B.DIM_DATE
        JOIN DATA.VT_C_DIM_MATERIAL C ON C.DIM_MATERIAL = A.DIM_MATERIAL
        JOIN DATA.VT_C_DIM_SUPPLIER D ON D.DIM_SUPPLIER = A.DIM_SUPPLIER
        JOIN DATA.VT_DIM_SUPPLIERCOUNTRY E ON E.DIM_COUNTRY = A.DIM_COUNTRY
        JOIN DATA.VT_DIM_INCOTERM F ON F.DIM_INCOTERM = A.DIM_INCOTERM
        JOIN DATA.VT_DIM_PLANT G ON G.DIM_PLANT = A.DIM_PLANT
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SC ON SC.DIM_SOURCING_TREE = A.DIM_SOURCING_TREE
    WHERE
        YEAR(TO_DATE(B.DIM_DATE, 'YYYYMMDD')) = '2023'
        AND C.DIM_MATERIAL <> '-1'
        AND g.TXT_PLANT <>'#'
    GROUP BY
        C.TXT_MATERIAL,
        A.DIM_MATERIAL,
        A.DIM_SUPPLIER,
        D.TXT_CONS_SUPPLIER_L1,
        E.TXT_COUNTRY,
        F.TXT_INCOTERM,
        G.TXT_PLANT,
        A.DIM_COUNTRY,
        A.DIM_INCOTERM,
        A.DIM_PLANT,
        SC.TXT_CATEGORY_LEVEL_2,
        YEAR(TO_DATE(B.DIM_DATE, 'YYYYMMDD')),
        MONTHNAME(TO_DATE(B.DIM_DATE, 'YYYYMMDD')),
        QUARTER(TO_DATE(B.DIM_DATE, 'YYYYMMDD'))
),
MIN_PRICE_TABLE AS (
    SELECT
        YEAR_,
        QUARTER,
        MONTH,
        DIM_MATERIAL,
        TXT_COUNTRY,
        DIM_INCOTERM,
        DIM_PLANT,
        DIM_COUNTRY,
        MIN(PRICE_AVG) AS MIN_AVG_PRICE
    FROM
        BASE_TABLE
    GROUP BY
       YEAR_,
       QUARTER,
       MONTH,
       DIM_MATERIAL,
       TXT_COUNTRY,
       DIM_COUNTRY,
       DIM_INCOTERM,
       DIM_PLANT
),
MIN_PRICE_AVG AS (
    SELECT
        A.YEAR_ AS YEAR,
        A.QUARTER,
        A.MONTH,
        A.CATEGORY,
        A.TXT_MATERIAL,
        A.DIM_MATERIAL,
        A.DIM_SUPPLIER,
        A.TXT_CONS_SUPPLIER_L1,
        A.TXT_COUNTRY,
        A.TXT_INCOTERM,
        A.TXT_PLANT,
        A.DIM_COUNTRY,
        A.DIM_INCOTERM,
        A.DIM_PLANT,
        SPEND,
        QUANTITY,
        PRICE_AVG AS PRICE_AVERAGE,
        B.MIN_AVG_PRICE
    FROM
        BASE_TABLE A
        JOIN MIN_PRICE_TABLE B ON B.YEAR_ = A.YEAR_ AND B.QUARTER =  A.QUARTER AND B.MONTH = A.MONTH AND B.DIM_MATERIAL = A.DIM_MATERIAL
        AND B.DIM_COUNTRY = A.DIM_COUNTRY AND A.DIM_INCOTERM=B.DIM_INCOTERM AND A.DIM_PLANT=B.DIM_PLANT
),
PRICE_ARB_TBL AS ( SELECT
    MONTH,
    TRIM(CATEGORY) AS CATEGORY,
    TRIM(TXT_COUNTRY) AS COUNTRY,
    TRIM(TXT_CONS_SUPPLIER_L1) AS SUPPLIER,
    TRIM(TXT_MATERIAL) AS MATERIAL,
    SUM(SPEND) AS SPEND,
    SUM(QUANTITY) AS QUANTITY,
    ROUND (CASE
        WHEN SUM(QUANTITY) > 0 THEN SUM(SPEND) / SUM(QUANTITY)
        ELSE 0
    END,2) AS PRICE_AVG,
    MIN(MIN_AVG_PRICE) AS MIN_AVG_PRICE
    FROM
        MIN_PRICE_AVG
    GROUP BY
        MONTH,
        CATEGORY,
        COUNTRY,
        SUPPLIER,
        MATERIAL
)
SELECT
    MONTH,
    CATEGORY,
    COUNTRY,
    SUPPLIER,
    MATERIAL,
    SPEND,
    QUANTITY,
    PRICE_AVG,
    MIN_AVG_PRICE,
    ROUND((SPEND - (QUANTITY * MIN_AVG_PRICE)), 2) AS PRICE_ARBITRAGE,
    CASE 
        WHEN SPEND>0 THEN ROUND(((SPEND - (QUANTITY * MIN_AVG_PRICE)) * 100 / SPEND),2) 
        ELSE 0 END AS PRICE_ARBITRAGE_PERCENTAGE
FROM PRICE_ARB_TBL
WHERE LOWER(MATERIAL) = LOWER('SCREWS') AND LOWER(COUNTRY) = LOWER('SOUTH AFRICA')
ORDER BY PRICE_ARBITRAGE DESC;

