
WITH DIFFPAYMENT AS (
    SELECT
        YEAR(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SC.TXT_COUNTRY,
        G.TXT_PLANT, 
        C.TXT_MATERIAL,
        SUP.TXT_CONS_SUPPLIER_L1 AS SUPPLIER,
        PT.txt_cons_payment_term as PAYMENT_TERM_GROUP,
        NULLIF(COUNT(MES_INTEGER), 0) AS MES_COUNT,
        SUM(IP.MES_DIFF_EARLY_PAYMENT) AS MES_DIFF_EARLY_PAYMENT,
        SUM(IP.MES_SPEND_PAID_CURR_1) AS TOTAL_SPEND,
        SUM(IP.mes_diff_invoice_payment_date_weighted) AS Mes_diff_invoice_payment_date_weighted,
        SUM(MES_DIFF_EARLY_PAYMENT) / NULLIF(COUNT(MES_INTEGER), 0) AS Diff_Early_Payment,
        10 as WACC,
        com.txt_level_4
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_PAYMENT AS IP
        LEFT OUTER JOIN DATA.VT_C_DIM_SUPPLIER AS SUP ON SUP.DIM_SUPPLIER = IP.DIM_SUPPLIER
        LEFT OUTER JOIN DATA.VT_C_DIM_MATERIAL AS C ON C.DIM_MATERIAL = IP.DIM_MATERIAL
        LEFT OUTER JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME AS SOUR ON SOUR.DIM_SOURCING_TREE = IP.DIM_SOURCING_TREE
        LEFT OUTER JOIN DATA.VT_DIM_PERIOD VDP ON VDP.DIM_DATE = IP.DIM_DATE
        LEFT OUTER JOIN DATA.VT_DIM_SupplierCountry SC ON IP.DIM_COUNTRY=SC.DIM_COUNTRY
        LEFT OUTER JOIN DATA.VT_DIM_COMPANY COM on IP.DIM_COMPANY=COM.DIM_COMPANY
        LEFT OUTER JOIN data.VT_DIM_PLANT G ON IP.DIM_PLANT = G.DIM_PLANT
        LEFT OUTER JOIN  DATA.VT_DIM_PAYMENTTERM AS PT ON PT.DIM_PAYMENT_TERM = IP.DIM_PAYMENT_TERM
    WHERE
        IP.DIM_VALUE_TYPE = 'P'
        AND LOWER(PT.TXT_PAYMENT_TERM_TYPE) = LOWER('NET PAYMENT')
        AND G.TXT_PLANT <> '#'
        AND YEAR(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
    GROUP BY
        SUP.TXT_CONS_SUPPLIER_L1,
        YEAR(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        sc.TXT_COUNTRY,
        g.TXT_PLANT,
        c.TXT_MATERIAL,
        pt.txt_cons_payment_term,
        com.txt_level_4     
)
SELECT
    YEAR,
    CATEGORY
    SUPPLIER,
    ROUND(SUM(
        CASE
            WHEN DP.MES_DIFF_EARLY_PAYMENT < -3 THEN (DP.TOTAL_SPEND * DP.DIFF_EARLY_PAYMENT * 0.1 * -1) / 365
            ELSE 0
        END
    ),2)AS EARLY_PAYMENT
FROM
    DIFFPAYMENT AS DP
GROUP BY
    YEAR,
    CATEGORY,
    SUPPLIER
ORDER BY
    EARLY_PAYMENT DESC