WITH PAYMENTDETAILS AS (
    SELECT
        YEAR(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        QUARTER(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) AS QUARTER,
        Month(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) AS Month,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        t2.TXT_CONS_SUPPLIER_L1 as SUPPLIER,
        sc.TXT_COUNTRY AS COUNTRY,
        f.TXT_INCOTERM_ABB AS INCOTERM,
        g.TXT_PLANT AS PLANT,
        com.TXT_LEVEL_4 AS COMPANY,
        MAT.TXT_MATERIAL AS MATERIAL,
        PT.TXT_CONS_PAYMENT_TERM AS PaymentTermGroup,
        pt.TXT_PAYMENT_TERM_TYPE as PaymentTerm,
        SUM(FP.MES_SPEND_PAID_CURR_1) AS SPEND,
        SUM(FP.MES_DIFF_INVOICE_PAYMENT_DATE) AS TOTALPAYMENTDATEDIFF,
        SUM(fp.mes_diff_invoice_payment_date_weighted) AS Mes_diff_invoice_payment_date_weighted,
        COUNT(FP.MES_INTEGER) AS PAYMENTCOUNT,
        MAX(PT.NUM_DAYS_NET) AS NUM_DAYS,
        GREATEST(
            (
                SUM(FP.MES_DIFF_INVOICE_PAYMENT_DATE) / COUNT(FP.MES_INTEGER)
            ),
            MAX(PT.NUM_DAYS_NET)
        ) AS MAXPAYMENTDAYS        
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_PAYMENT FP
        JOIN DATA.VT_DIM_PAYMENTTERM PT ON FP.DIM_PAYMENT_TERM = PT.DIM_PAYMENT_TERM
        JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = FP.DIM_MATERIAL
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = FP.DIM_SOURCING_TREE
        JOIN DATA.VT_DIM_PERIOD VDP ON VDP.DIM_DATE = FP.DIM_DATE
        JOIN data.VT_C_DIM_ValueType vdv ON vdv.DIM_VALUE_TYPE = fp.DIM_VALUE_TYPE
        JOIN data.VT_C_DIM_Supplier t2 on fp.DIM_SUPPLIER = t2.DIM_SUPPLIER
        JOIN data.VT_DIM_SupplierCountry sc ON fp.DIM_COUNTRY=sc.DIM_COUNTRY 
        JOIN data.VT_DIM_Incoterm f ON fp.DIM_INCOTERM = f.DIM_INCOTERM
        JOIN data.vt_dim_plant g ON fp.dim_plant = g.dim_plant
        JOIN data.VT_DIM_COMPANY com on fp.DIM_COMPANY=com.DIM_COMPANY
    WHERE vdv.DIM_VALUE_TYPE = 'P'
        and g.TXT_PLANT <> '#'
        and fp.DIM_MATERIAL <>'-1'
        AND YEAR(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
    GROUP BY
        YEAR(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')),
        QUARTER(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')),
        Month(TO_DATE(VDP.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        t2.TXT_CONS_SUPPLIER_L1,
        sc.TXT_COUNTRY,
        f.TXT_INCOTERM_ABB,
        g.TXT_PLANT,
        com.TXT_LEVEL_4,
        MAT.TXT_MATERIAL,
        pt.TXT_PAYMENT_TERM_TYPE,
        pt.TXT_CONS_PAYMENT_TERM
)
SELECT
    YEAR,
    CATEGORY,
    SUPPLIER,
    0.1 AS WACC,
    SUM(PD.MAXPAYMENTDAYS) AS MAX_PAYMENT_DAYS,
    SUM(PD.SPEND) AS TOTAL_SPEND,
    SUM(
    CASE
        WHEN (90 - MAXPAYMENTDAYS) > 0 THEN (
            PD.SPEND * (90 - COALESCE(MAXPAYMENTDAYS, 90)) * (0.1 / 365)
        )
        ELSE (
          0
        )
    END) AS POTENTIALSAVINGS
FROM
    PAYMENTDETAILS PD
GROUP BY 
YEAR, CATEGORY, SUPPLIER
ORDER BY YEAR DESC, POTENTIALSAVINGS DESC