WITH HCCDATA AS (
	SELECT
		YEAR(TO_DATE(P.DIM_DATE, 'YYYYMMDD')) AS YEAR,
		SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
		sc.TXT_COUNTRY AS COUNTRY,
		mat.TXT_MATERIAL AS MATERIAL,
		SUP.TXT_CONS_SUPPLIER_L1 AS SUPPLIER,
		g.TXT_PLANT AS PLANT,
		PT.TXT_CONS_PAYMENT_TERM,
		SUM(FP.MES_SPEND_CURR_1) AS HCC_SPEND,
	FROM
		DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED FP
		JOIN DATA.VT_DIM_PAYMENTTERM PT ON PT.DIM_PAYMENT_TERM = FP.DIM_PAYMENT_TERM
		JOIN DATA.VT_DIM_SUPPLIERCOUNTRY SC ON SC.DIM_COUNTRY = FP.DIM_COUNTRY
		JOIN DATA.VT_DIM_PERIOD P ON P.DIM_DATE = FP.DIM_DATE
		JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = FP.DIM_SOURCING_TREE
		JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = FP.DIM_SUPPLIER
		JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = FP.DIM_MATERIAL
		JOIN DATA.VT_DIM_PLANT G ON G.DIM_PLANT = FP.DIM_PLANT
	WHERE
		LOWER(SC.TXT_LOW_COST_COUNTRY) = LOWER('HIGH COST COUNTRY')
		AND sc.TXT_LOW_COST_COUNTRY != '#' 
		AND fp.DIM_MATERIAL != '-1'
		AND fp.MES_SPEND_CURR_1> 0
		AND G.TXT_PLANT != '#'
	GROUP BY
		mat.TXT_MATERIAL,
		SUP.TXT_CONS_SUPPLIER_L1,
		g.TXT_PLANT,
		PT.TXT_CONS_PAYMENT_TERM,
		SC.TXT_COUNTRY,
		SOUR.TXT_CATEGORY_LEVEL_2,
		YEAR(TO_DATE(P.DIM_DATE, 'YYYYMMDD'))

),
HCCSAVINGSDATA AS (
	SELECT
		YEAR,
		CATEGORY,
		SUPPLIER,
		PLANT,
		COUNTRY,
		MATERIAL,
		HCC_SPEND,
		TXT_CONS_PAYMENT_TERM AS PAYMENT_TERM,
		HCC_SPEND * 0.8 AS HCC_TRANSFER_AMOUNT
	FROM
		HCCDATA HD
)
SELECT
	YEAR,
	CATEGORY,
	SUPPLIER,
	PAYMENT_TERM,
	ROUND(SUM(HCC_SPEND), 2) AS HCC_SPEND,
	ROUND(SUM(HCC_TRANSFER_AMOUNT), 2) AS HCC_TRANSFER_AMOUNT,
	ROUND(SUM(HCC_TRANSFER_AMOUNT) * 0.1, 2) AS HCC_TO_LCC_OPPORTUNITY
FROM
	HCCSAVINGSDATA
GROUP BY 
	YEAR,
	CATEGORY,
	SUPPLIER,
	PAYMENT_TERM
ORDER BY
	YEAR DESC,
	HCC_TO_LCC_OPPORTUNITY DESC