WITH SELECTED_PERIOD_DATA AS (
    SELECT
        QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        MIN(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS MIN_DATE,
        MAX(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS MAX_DATE
    FROM
        DATA.VT_DIM_PERIOD AS PER
    WHERE
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = 2024
    GROUP BY
        QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD'))
),
OVERALL_SPENDS_SHARE AS (
    SELECT
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS SELECTED_YEAR,
        QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS SELECTED_QUARTER,
        (SELECT SUM(FIP2.MES_SPEND_CURR_1)
     FROM DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED FIP2) AS TOTAL_SPEND,
        SUM(FIP.MES_SPEND_CURR_1) AS SPEND_BY_YEAR,
        SUM(FIP.MES_QUANTITY) AS TOTAL_QUANTITY
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED FIP
        JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = FIP.DIM_DATE
    WHERE
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) IN (
            SELECT
                YEAR(MIN_DATE)
            FROM
                SELECTED_PERIOD_DATA
        )
        AND MONTH(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) IN (
            SELECT
                MONTH(MIN_DATE)
            FROM
                SELECTED_PERIOD_DATA
        )
    GROUP BY
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD'))
),
SELECTED_PURCHASE_PRICE AS (
    SELECT
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS SELECTED_YEAR,
        QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS SELECTED_QUARTER,
        SC.TXT_COUNTRY AS COUNTRY,
        PL.TXT_PLANT AS PLANT,
        ST.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        MAT.TXT_MATERIAL AS MATERIAL,
        SUP.TXT_CONS_SUPPLIER_L1 AS SUPPLIER,
        SUM(FIP.MES_SPEND_CURR_1) AS SPENDS,
        SUM(FIP.MES_QUANTITY) AS QUANTITY,
        CASE
            WHEN SUM(FIP.MES_SPEND_CURR_1) * SUM(FIP.MES_QUANTITY) > 0 THEN ABS(SUM(FIP.MES_SPEND_CURR_1)) / ABS(SUM(FIP.MES_QUANTITY))
            ELSE 0
        END AS SELECTED_PURCHASE_PRICE
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED FIP
        JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = FIP.DIM_DATE
        JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = FIP.DIM_MATERIAL
        JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = FIP.DIM_SUPPLIER
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME ST ON FIP.DIM_SOURCING_TREE = ST.DIM_SOURCING_TREE
        JOIN DATA.VT_DIM_PLANT PL ON PL.DIM_PLANT = FIP.DIM_PLANT
        JOIN DATA.VT_DIM_SUPPLIERCOUNTRY SC ON SC.DIM_COUNTRY = FIP.DIM_COUNTRY
    WHERE
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) IN (
            SELECT
                YEAR(MIN_DATE)
            FROM
                SELECTED_PERIOD_DATA
        )
        AND MONTH(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) IN (
            SELECT
                MONTH(MIN_DATE)
            FROM
                SELECTED_PERIOD_DATA
        )
    GROUP BY
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        SC.TXT_COUNTRY,
        PL.TXT_PLANT,
        ST.TXT_CATEGORY_LEVEL_2,
        MAT.TXT_MATERIAL,
        SUP.TXT_CONS_SUPPLIER_L1
),
PREVIOUS_PURCHASE_PRICE AS (
    SELECT
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS PREVIOUS_YEAR,
        QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS PREVIOUS_QUARTER,
        ST.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SC.TXT_COUNTRY AS COUNTRY,
        PL.TXT_PLANT AS PLANT,
        MAT.TXT_MATERIAL AS MATERIAL,
        SUP.TXT_CONS_SUPPLIER_L1 AS SUPPLIER,
        SUM(FIP.MES_SPEND_CURR_1) AS SPENDS,
        SUM(FIP.MES_QUANTITY) AS QUANTITY,
        CASE
            WHEN SUM(FIP.MES_SPEND_CURR_1) * SUM(FIP.MES_QUANTITY) > 0 THEN ABS(SUM(FIP.MES_SPEND_CURR_1)) / ABS(SUM(FIP.MES_QUANTITY))
            ELSE 0
        END AS PREVIOUS_PURCHASE_PRICE
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED FIP
        JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = FIP.DIM_DATE
        JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = FIP.DIM_MATERIAL
        JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = FIP.DIM_SUPPLIER
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME ST ON FIP.DIM_SOURCING_TREE = ST.DIM_SOURCING_TREE
        JOIN DATA.VT_DIM_PLANT PL ON PL.DIM_PLANT = FIP.DIM_PLANT
        JOIN DATA.VT_DIM_SUPPLIERCOUNTRY SC ON SC.DIM_COUNTRY = FIP.DIM_COUNTRY
    WHERE
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) IN (
            SELECT
                YEAR(MIN_DATE)-1
            FROM
                SELECTED_PERIOD_DATA
        )
        AND MONTH(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = 12
    GROUP BY
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        SC.TXT_COUNTRY,
        PL.TXT_PLANT,
        ST.TXT_CATEGORY_LEVEL_2,
        MAT.TXT_MATERIAL,
        SUP.TXT_CONS_SUPPLIER_L1
),
PRICE_AVERAGE_DATA AS (
    SELECT SELECTED_YEAR, SELECTED_QUARTER, SPP.PLANT, SPP.COUNTRY, SPP.CATEGORY, SPP.MATERIAL, SPP.SUPPLIER, ROUND(SELECTED_PURCHASE_PRICE,2) AS SELECTED_PURCHASE_PRICE, ROUND(PREVIOUS_PURCHASE_PRICE,2) AS PREVIOUS_PURCHASE_PRICE, ROUND(((SELECTED_PURCHASE_PRICE-PREVIOUS_PURCHASE_PRICE)/PREVIOUS_PURCHASE_PRICE), 2) AS PRICE_AVERAGE_CHANGE
    FROM SELECTED_PURCHASE_PRICE SPP
    JOIN PREVIOUS_PURCHASE_PRICE PPP
    ON  SPP.CATEGORY = PPP.CATEGORY
    AND  SPP.PLANT = PPP.PLANT
    AND SPP.COUNTRY = PPP.COUNTRY
    AND SPP.MATERIAL = PPP.MATERIAL  
    AND SPP.SUPPLIER = PPP.SUPPLIER
 WHERE PREVIOUS_PURCHASE_PRICE > 0 
)
SELECT PRI.SELECTED_YEAR, PRI.SELECTED_QUARTER, COUNTRY, PLANT, CATEGORY, MATERIAL, SUPPLIER, SELECTED_PURCHASE_PRICE, PREVIOUS_PURCHASE_PRICE, PRICE_AVERAGE_CHANGE, ROUND(((PRICE_AVERAGE_CHANGE *100)/(SPEND_BY_YEAR/TOTAL_SPEND)),5) AS PRICE_VOLATILITY
FROM PRICE_AVERAGE_DATA PRI
JOIN OVERALL_SPENDS_SHARE OSS
ON PRI.SELECTED_YEAR = OSS.SELECTED_YEAR 
AND PRI.SELECTED_QUARTER = OSS.SELECTED_QUARTER
ORDER BY PRICE_VOLATILITY DESC