WITH
    INCO_DATA AS (
        SELECT
            YEAR (TO_DATE (B.DIM_DATE, 'YYYYMMDD')) AS YEAR,
            SC.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
            D.TXT_SUPPLIER AS SUPPLIER,
            E.TXT_COUNTRY AS COUNTRY,
            G.TXT_PLANT AS PLANT,
            A.DIM_UOM AS UOM,
            ROUND(COALESCE(SUM(A.MES_SPEND_CURR_1), 0), 2) AS SPEND,
            COALESCE(SUM(A.MES_QUANTITY), 0) AS QUANTITY,
            CASE
                WHEN SUM(A.MES_QUANTITY) > 0 THEN SUM(A.MES_SPEND_CURR_1) / SUM(A.MES_QUANTITY)
                ELSE 0
            END AS UNIT_PRICE,
            COUNT(DISTINCT A.DIM_INCOTERM) AS INCOTERM_COUNT
        FROM
            DATA.VT_C_FACT_GRN_ORDERPOSITION A
            JOIN DATA.VT_DIM_PERIOD B ON B.DIM_DATE = A.DIM_DATE
            JOIN DATA.VT_C_DIM_SUPPLIER D ON D.DIM_SUPPLIER = A.DIM_SUPPLIER
            JOIN DATA.VT_DIM_SUPPLIERCOUNTRY E ON E.DIM_COUNTRY = A.DIM_COUNTRY
            JOIN DATA.VT_DIM_PLANT G ON G.DIM_PLANT = A.DIM_PLANT
            JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SC ON SC.DIM_SOURCING_TREE = A.DIM_SOURCING_TREE
            JOIN DATA.VT_C_DIM_ORDERDOCUMENTTYPE DT ON A.DIM_DOCUMENT_TYPE = DT.DIM_DOCUMENT_TYPE
        WHERE
            G.TXT_PLANT in (
                'Emirates Aluminium Company',
                'Dubai Aluminium PJSC',
                'Al Taweelah Alumina LLC'
            )
            AND DT.DIM_DOCUMENT_TYPE in ('DSP100.F.CP', 'DSP100.F.NB', 'DSP100.F.ST')
            AND YEAR (TO_DATE (B.DIM_DATE, 'YYYYMMDD')) = YEAR (CURRENT_DATE)
            AND LOWER(SC.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
        GROUP BY
            D.TXT_SUPPLIER,
            G.TXT_PLANT,
            E.TXT_COUNTRY,
            SC.TXT_CATEGORY_LEVEL_2,
            A.DIM_UOM,
            YEAR (TO_DATE (B.DIM_DATE, 'YYYYMMDD'))
    )
SELECT
    YEAR,
    CATEGORY,
    SUPPLIER,
    COUNTRY,
    PLANT,
    UOM,
    SPEND,
    QUANTITY,
    UNIT_PRICE,
    INCOTERM_COUNT
FROM
    INCO_DATA
WHERE
    INCOTERM_COUNT >= 2