SELECT 
    YEAR,
    CATEGORY,
    SUM(PRICE_ARBITRAGE) AS PRICE_ARBITRAGE
FROM 
    DATA.T_C_PRICE_ARBITRAGE
WHERE YEAR = YEAR(CURRENT_DATE) AND LOWER(CATEGORY) = LOWER('Valves')
GROUP BY  
    CATEGORY,
    YEAR