WITH SINGLE_SOURCE_MATERIAL_DATA AS (
    SELECT
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        COUNT(DISTINCT IVP.DIM_SUPPLIER) AS SUPPLIER_COUNT,
        MAT.DIM_MATERIAL AS MATERIAL_ID,
        MAT.TXT_MATERIAL AS MATERIAL,
        SUM(MES_SPEND_CURR_1) AS TOTAL_SPEND
    FROM
        DATA.VT_C_FACT_GRN_ORDERPOSITION IVP
        JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
        JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
        JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = IVP.DIM_MATERIAL
        JOIN DATA.VT_C_DIM_ORDERDOCUMENTTYPE ODT ON ODT.DIM_DOCUMENT_TYPE = IVP.DIM_DOCUMENT_TYPE
        JOIN DATA.VT_DIM_PLANT PL ON PL.DIM_PLANT = IVP.DIM_PLANT
    WHERE
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
         AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
         AND PL.TXT_PLANT IN ('Al Taweelah Alumina LLC','Dubai Aluminium PJSC','Emirates Aluminium Company')
         AND ODT.DIM_DOCUMENT_TYPE IN ('DSP100.F.CP','DSP100.F.NB','DSP100.F.ST')
    GROUP BY 
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        MAT.DIM_MATERIAL,
        MAT.TXT_MATERIAL
    HAVING SUPPLIER_COUNT = 1
    ORDER BY TOTAL_SPEND DESC
),
TOTAL_DATA AS (
    SELECT
        YEAR,
        CATEGORY,
        MATERIAL,
        SUM(SPENDS) AS SPEND,
        SUM(QUANTITY) AS QUANTITY,
        SUM(PRICE_ARBITRAGE) AS PRICE_ARBITRAGE,
        SUM(OEM_NON_OEM_OPPORTUNITY) AS OEM_NON_OEM_OPPORTUNITY,
        SUM(HCC_TO_LCC_OPPORTUNITY) AS HCC_TO_LCC_OPPORTUNITY,
        SUM(PRICE_BENCHMARK_OPPORTUNITY) AS PRICE_BENCHMARK_OPPORTUNITY,
        SUM(TOTAL_OPPORTUNITY) AS TOTAL_OPPORTUNITY
    FROM
        DATA.T_C_TOTAL_SAVINGS_OPPORTUNITY
    WHERE YEAR = YEAR(CURRENT_DATE)
    AND LOWER(CATEGORY) = LOWER('Valves')
    GROUP BY 
        YEAR,
        CATEGORY,
        MATERIAL
    ORDER BY TOTAL_OPPORTUNITY DESC
)
SELECT 
    SD.YEAR,
    SD.CATEGORY,
    SD.MATERIAL,
    TOTAL_OPPORTUNITY AS TOTAL_OPPORTUNITY
FROM SINGLE_SOURCE_MATERIAL_DATA SD
LEFT JOIN TOTAL_DATA TD ON SD.YEAR = TD.YEAR AND SD.CATEGORY = TD.CATEGORY AND SD.MATERIAL = TD.MATERIAL
ORDER BY TOTAL_OPPORTUNITY DESC