SELECT
    YEAR,
    CATEGORY,
    SUPPLIER,
    COALESCE(SUM(SPEND), 0) AS SPEND,
    COALESCE(SUM(OEM_SPEND), 0) AS OEM_SPEND,
    COALESCE(SUM(OEM_BENCHMARK_SAVING * 0.4), 0) AS OEM_NONOEM_OPPORTUNITY
FROM
     DATA.T_C_OEM_NON_OEM
WHERE YEAR = YEAR(CURRENT_DATE) AND LOWER(CATEGORY) = LOWER('Valves')
GROUP BY
    YEAR,
    CATEGORY,
    SUPPLIER
ORDER BY
    OEM_NONOEM_OPPORTUNITY DESC