SELECT 
    YEAR,
    CATEGORY,
    SUM(SPEND) AS TOTAL_SPEND,
    SUM(PRICE_ARBITRAGE) AS PRICE_ARBITRAGE,
    (SUM(SPEND)-SUM(PRICE_ARBITRAGE)) AS PRICE_ARBITRAGE_EXPECTED_SPEND
FROM 
    DATA.T_C_PRICE_ARBITRAGE
WHERE YEAR = YEAR(CURRENT_DATE) AND LOWER(CATEGORY) = LOWER('Valves')
GROUP BY
    YEAR,
    CATEGORY