SELECT
    YEAR (TO_DATE (B.DIM_DATE, 'YYYYMMDD')) AS YEAR,
    SC.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
    ROUND(COALESCE(SUM(A.MES_SPEND_CURR_1), 0), 2) AS SPEND,
    COALESCE(SUM(A.MES_QUANTITY), 0) AS QUANTITY,
    COALESCE(COUNT(A.DIM_ORDER_POSITION), 0) AS PO_LINES_COUNT
FROM
    DATA.VT_C_FACT_GRN_ORDERPOSITION A
    JOIN DATA.VT_DIM_PERIOD B ON B.DIM_DATE = A.DIM_DATE
    JOIN DATA.VT_C_DIM_SUPPLIER D ON D.DIM_SUPPLIER = A.DIM_SUPPLIER
    JOIN DATA.VT_DIM_SUPPLIERCOUNTRY E ON E.DIM_COUNTRY = A.DIM_COUNTRY
    JOIN DATA.VT_DIM_PLANT G ON G.DIM_PLANT = A.DIM_PLANT
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SC ON SC.DIM_SOURCING_TREE = A.DIM_SOURCING_TREE
    JOIN DATA.VT_C_DIM_ORDERDOCUMENTTYPE DT ON A.DIM_DOCUMENT_TYPE = DT.DIM_DOCUMENT_TYPE
    JOIN DATA.VT_DIM_PAYMENTTERM PT ON PT.DIM_PAYMENT_TERM = A.DIM_PAYMENT_TERM
WHERE
    G.TXT_PLANT in (
        'Emirates Aluminium Company',
        'Dubai Aluminium PJSC',
        'Al Taweelah Alumina LLC'
    )
    AND DT.DIM_DOCUMENT_TYPE in ('DSP100.F.CP', 'DSP100.F.NB', 'DSP100.F.ST')
    AND YEAR (TO_DATE (B.DIM_DATE, 'YYYYMMDD')) = YEAR (CURRENT_DATE)
    AND LOWER(SC.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
    AND PT.NUM_DAYS_NET >= 60
GROUP BY
    SC.TXT_CATEGORY_LEVEL_2,
    YEAR (TO_DATE (B.DIM_DATE, 'YYYYMMDD'))