WITH SUPPLIER_SPEND AS (
    SELECT
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SUP.DIM_SUPPLIER AS SUPPLIER_ID,
        SUP.TXT_SUPPLIER AS SUPPLIER_NAME,
        SUP.TXT_OEM_TYPE AS OEM_TYPE
    FROM
        DATA.VT_C_FACT_GRN_ORDERPOSITION AS GO
        JOIN DATA.VT_DIM_PERIOD AS PER ON PER.DIM_DATE = GO.DIM_DATE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME AS SOUR ON SOUR.DIM_SOURCING_TREE = GO.DIM_SOURCING_TREE
        JOIN DATA.VT_C_DIM_ORDERDOCUMENTTYPE AS ODT ON ODT.DIM_DOCUMENT_TYPE = GO.DIM_DOCUMENT_TYPE
        JOIN DATA.VT_DIM_PLANT AS PL ON PL.DIM_PLANT = GO.DIM_PLANT
        JOIN DATA.VT_C_DIM_SUPPLIER AS SUP ON SUP.DIM_SUPPLIER = GO.DIM_SUPPLIER
    WHERE
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
        AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
        AND PL.TXT_PLANT IN (
            'Al Taweelah Alumina LLC',
            'Dubai Aluminium PJSC',
            'Emirates Aluminium Company'
        )
        AND ODT.DIM_DOCUMENT_TYPE IN ('DSP100.F.CP', 'DSP100.F.NB', 'DSP100.F.ST')
        AND SUP.TXT_OEM_TYPE IN ('OEM', 'Non-OEM')
    GROUP BY
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        SUP.DIM_SUPPLIER,
        SUP.TXT_SUPPLIER,
        SUP.TXT_OEM_TYPE
)
SELECT
    YEAR,
    CATEGORY,
    COUNT(DISTINCT CASE WHEN OEM_TYPE='OEM' THEN SUPPLIER_ID END) AS OEM_SUPPLIERS,
    COUNT(DISTINCT CASE WHEN OEM_TYPE='Non-OEM' THEN SUPPLIER_ID END) AS NON_OEM_SUPPLIERS
FROM
    SUPPLIER_SPEND
GROUP BY
    YEAR,
    CATEGORY