WITH SUPPLIER_SPEND AS (
    SELECT 
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SUP.DIM_SUPPLIER AS SUPPLIER_ID,
        SUP.TXT_SUPPLIER AS SUPPLIER_NAME,
        SUM(GO.MES_SPEND_CURR_1) AS SPEND
    FROM DATA.VT_C_FACT_GRN_ORDERPOSITION GO
    JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = GO.DIM_DATE
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = GO.DIM_SOURCING_TREE
    JOIN DATA.VT_C_DIM_ORDERDOCUMENTTYPE ODT ON ODT.DIM_DOCUMENT_TYPE = GO.DIM_DOCUMENT_TYPE
    JOIN DATA.VT_DIM_PLANT PL ON PL.DIM_PLANT = GO.DIM_PLANT
    JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = GO.DIM_SUPPLIER
    WHERE YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
     AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Batteries')
     AND PL.TXT_PLANT IN ('Al Taweelah Alumina LLC','Dubai Aluminium PJSC','Emirates Aluminium Company')
     AND ODT.DIM_DOCUMENT_TYPE IN ('DSP100.F.CP','DSP100.F.NB','DSP100.F.ST')
    GROUP BY 
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        SUP.DIM_SUPPLIER,
        SUP.TXT_SUPPLIER 
),
TOTAL_SPEND AS (
    SELECT 
        YEAR,
        CATEGORY,
        SUM(SPEND) AS TOTAL_SPEND
    FROM SUPPLIER_SPEND
     GROUP BY
        YEAR,
        CATEGORY
),
SUPPLIER_RANKED AS (
    SELECT 
        SUP.YEAR,
        SUP.CATEGORY,
        SUP.SUPPLIER_ID,
        SUP.SUPPLIER_NAME,
        SUP.SPEND,
        TOTAL.TOTAL_SPEND,
        SUM(ROUND(SUP.SPEND,0)) OVER (PARTITION BY SUP.YEAR, SUP.CATEGORY ORDER BY ROUND(SUP.SPEND,0) DESC) AS CUMULATIVE_SPEND,
        (SUM(ROUND(SUP.SPEND,0)) OVER (PARTITION BY SUP.YEAR, SUP.CATEGORY ORDER BY ROUND(SUP.SPEND,0) DESC) / ROUND(TOTAL.TOTAL_SPEND,0)) * 100 AS CUMULATIVE_PERCENTAGE
    FROM SUPPLIER_SPEND SUP
    JOIN TOTAL_SPEND TOTAL ON SUP.YEAR = TOTAL.YEAR AND SUP.CATEGORY = TOTAL.CATEGORY
    ORDER BY SUP.SPEND DESC
)
SELECT 
    YEAR,
    CATEGORY,
    COUNT(DISTINCT SUPPLIER_ID) AS TOTAL_SUPPLIERS,
    MAX(TOTAL_SPEND) AS TOTAL_SPEND,
    SUM(CASE WHEN CUMULATIVE_PERCENTAGE <= 80 THEN SPEND ELSE 0 END) AS KEY_SUPPLIER_SPEND,
    COUNT(DISTINCT CASE WHEN CUMULATIVE_PERCENTAGE <= 80 THEN SUPPLIER_ID END)+1 AS KEY_SUPPLIERS,
    (MAX(TOTAL_SPEND)-KEY_SUPPLIER_SPEND) AS TAIL_SUPPLIER_SPEND,
    (TOTAL_SUPPLIERS-KEY_SUPPLIERS) AS TAIL_SUPPLIERS
FROM SUPPLIER_RANKED
GROUP BY YEAR,
    CATEGORY
ORDER BY TOTAL_SPEND DESC;