WITH PO_CONTRACT_DATA AS (
    SELECT
        YEAR(TO_DATE(B.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SC.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        A.DIM_ORDER_POSITION AS CONTRACT_PURCHASE_ORDER,
        TO_DATE(CP.DIM_CONTRACT_END_DATE,'YYYYMMDD') AS CONTRACT_END_DATE
    FROM
        DATA.VT_C_FACT_GRN_ORDERPOSITION AS A
        JOIN DATA.VT_C_DIM_CONTRACT_POSITION AS CP ON A.DIM_CONTRACT_POSITION = CP.DIM_CONTRACT_POSITION
        JOIN DATA.VT_DIM_PERIOD AS B ON B.DIM_DATE = A.DIM_DATE
        JOIN DATA.VT_C_DIM_ORDERDOCUMENTTYPE AS DT ON A.DIM_DOCUMENT_TYPE = DT.DIM_DOCUMENT_TYPE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME AS SC ON SC.DIM_SOURCING_TREE = A.DIM_SOURCING_TREE
        JOIN DATA.VT_DIM_PLANT AS P ON A.DIM_PLANT = P.DIM_PLANT
    WHERE
        P.TXT_PLANT IN (
            'Emirates Aluminium Company',
            'Dubai Aluminium PJSC',
            'Al Taweelah Alumina LLC'
        )
        AND DT.DIM_DOCUMENT_TYPE IN ('DSP100.F.CP', 'DSP100.F.NB', 'DSP100.F.ST')
        AND CP.ORDER_NUMBER <> '-1'
        AND MES_SPEND_CURR_1 > 0
        AND TO_DATE(CP.DIM_CONTRACT_END_DATE,'YYYYMMDD') >= CURRENT_DATE
)
SELECT 
    YEAR,
    CATEGORY,
    COUNT(DISTINCT CONTRACT_PURCHASE_ORDER) AS CONTRACT_PURCHASE_ORDER
FROM PO_CONTRACT_DATA
WHERE
    YEAR = YEAR(CURRENT_DATE)
    AND LOWER(CATEGORY) = LOWER('Valves')
GROUP BY
    YEAR,
    CATEGORY