WITH TOTAL_DATA AS (
    SELECT
        YEAR(TO_DATE (B.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SC.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SUM(MES_SPEND_CURR_1) AS SPEND,
        COUNT(DISTINCT MAT.DIM_MATERIAL) AS TOTAL_MATERIAL
    FROM
        DATA.VT_C_FACT_GRN_ORDERPOSITION A
        JOIN DATA.VT_DIM_PERIOD B ON B.DIM_DATE = A.DIM_DATE
        JOIN DATA.VT_C_DIM_SUPPLIER D ON D.DIM_SUPPLIER = A.DIM_SUPPLIER
        JOIN DATA.VT_C_DIM_ORDERDOCUMENTTYPE DT ON A.DIM_DOCUMENT_TYPE = DT.DIM_DOCUMENT_TYPE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SC ON SC.DIM_SOURCING_TREE = A.DIM_SOURCING_TREE
        JOIN DATA.VT_DIM_SUPPLIERCOUNTRY SUP ON A.DIM_COUNTRY = SUP.DIM_COUNTRY
        JOIN DATA.VT_DIM_PLANT P ON A.DIM_PLANT = P.DIM_PLANT
        JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = A.DIM_MATERIAL
    WHERE
        P.TXT_PLANT IN (
            'Emirates Aluminium Company',
            'Dubai Aluminium PJSC',
            'Al Taweelah Alumina LLC'
        )
        AND DT.DIM_DOCUMENT_TYPE IN ('DSP100.F.CP', 'DSP100.F.NB', 'DSP100.F.ST')
        AND MES_SPEND_CURR_1 > 0
        AND YEAR(TO_DATE (B.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
        AND LOWER(SC.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
    GROUP BY
        YEAR(TO_DATE (B.DIM_DATE, 'YYYYMMDD')),
        SC.TXT_CATEGORY_LEVEL_2
),
CONTRACT_DATA AS (
    SELECT
        YEAR(TO_DATE (B.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SC.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SUM(MES_SPEND_CURR_1) AS CONTRACTED_SPEND,
        COUNT(DISTINCT MAT.DIM_MATERIAL) AS CONTRACTED_MATERIAL
    FROM
        DATA.VT_C_FACT_GRN_ORDERPOSITION A
        JOIN DATA.VT_C_DIM_CONTRACT_POSITION CP ON A.DIM_CONTRACT_POSITION = CP.DIM_CONTRACT_POSITION
        JOIN DATA.VT_DIM_PERIOD B ON B.DIM_DATE = A.DIM_DATE
        JOIN DATA.VT_C_DIM_SUPPLIER D ON D.DIM_SUPPLIER = A.DIM_SUPPLIER
        JOIN DATA.VT_C_DIM_ORDERDOCUMENTTYPE DT ON A.DIM_DOCUMENT_TYPE = DT.DIM_DOCUMENT_TYPE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SC ON SC.DIM_SOURCING_TREE = A.DIM_SOURCING_TREE
        JOIN DATA.VT_DIM_SUPPLIERCOUNTRY SUP ON A.DIM_COUNTRY = SUP.DIM_COUNTRY
        JOIN DATA.VT_DIM_PLANT P ON A.DIM_PLANT = P.DIM_PLANT
        JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = A.DIM_MATERIAL
    WHERE
        P.TXT_PLANT IN (
            'Emirates Aluminium Company',
            'Dubai Aluminium PJSC',
            'Al Taweelah Alumina LLC'
        )
        AND DT.DIM_DOCUMENT_TYPE IN ('DSP100.F.CP', 'DSP100.F.NB', 'DSP100.F.ST')
        AND LOWER(DT.TXT_DOCUMENT_TYPE) = LOWER('Call Off - Material') 
        AND CP.ORDER_NUMBER <> '-1'
        AND MES_SPEND_CURR_1 > 0
        AND YEAR(TO_DATE (B.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
        AND LOWER(SC.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
    GROUP BY
        YEAR(TO_DATE (B.DIM_DATE, 'YYYYMMDD')),
        SC.TXT_CATEGORY_LEVEL_2
)
SELECT TD.YEAR, TD.CATEGORY, ROUND(COALESCE(TD.SPEND, 0), 2) AS SPEND, ROUND(COALESCE(TD.TOTAL_MATERIAL, 0), 2) AS TOTAL_MATERIAL, ROUND(COALESCE(CD.CONTRACTED_SPEND, 0), 2) AS CONTRACT_SPEND,  ROUND(COALESCE(CD.CONTRACTED_MATERIAL, 0), 2) AS CONTRACT_MATERIAL, ROUND(COALESCE(TD.SPEND-CD.CONTRACTED_SPEND, 0), 2) AS NON_CONTRACT_SPEND, ROUND(COALESCE(TD.TOTAL_MATERIAL-CD.CONTRACTED_MATERIAL, 0), 2) AS NON_CONTRACT_MATERIAL
FROM TOTAL_DATA AS TD
LEFT JOIN CONTRACT_DATA AS CD
ON TD.YEAR = CD.YEAR
AND TD.CATEGORY = CD.CATEGORY