# PLEASE DO NOT REMOVE THIS FILE

# Storage Account Configuriation for "SourceAI GenAI development" service (branch: main)

# This file is used by PMCK to configure the storage accounts that are used in the Azure Resource Group
# You can add a new storage account by adding a new entry to the list below
# The name of the storage account must be unique and must contain only lowercase letters
# To update the Azure Resource group connect with the Tech Lead of Spendscape DS Team

# DO NOT DELETE ANY OF THE ENTRIES

ancillary_storage_accounts:
  - "920a2f73-c7db-405f-98ea-f768c6da864f" # Source AI Demo
