SELECT
    YEAR,
    CATEGORY,
    SUPPLIER,
    SUM(CLEANSHEET_OPPORTUNITY) AS CLEANSHEET_OPPORTUNITY,
    AVG(SPEND_SAVINGS_PERCENTAGE)*100 AS PCM_SAVINGS_PERCENTAGE
FROM DATA.T_C_PARAMETRIC_COST_MODELLING
WHERE YEAR = YEAR(CURRENT_DATE)
AND LOWER(CATEGORY) = LOWER('Valves')
GROUP BY 
    YEAR,
    CATEGORY,
    SUPPLIER
ORDER BY CLEANSHEET_OPPORTUNITY DESC