SELECT
    YEAR,
    CATEGORY,
    SUPPLIER,
    SUM(LPP_CORRUGATES_OPPORTUNITY) AS LPP_CORRUGATES_OPPORTUNITY
FROM
    DATA.T_C_LPP
WHERE
    LOWER(CATEGORY) = LOWER('Valves')
    AND YEAR = YEAR(CURRENT_DATE)
GROUP BY 
    YEAR,
    CATEGORY,
    SUPPLIER
ORDER BY 
    LPP_CORRUGATES_OPPORTUNITY DESC