WITH SINGLE_SOURCE_MATERIAL_DATA AS (
    SELECT
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        COUNT(DISTINCT IVP.DIM_SUPPLIER) AS SUPPLIER_COUNT,
        MAT.DIM_MATERIAL AS MATERIAL_ID,
        MAT.TXT_MATERIAL AS MATERIAL,
        SUM(MES_SPEND_CURR_1) AS TOTAL_SPEND
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
        JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
        JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
        JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = IVP.DIM_MATERIAL
    WHERE
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
         AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('CIBC')
         AND MAT.DIM_MATERIAL != '-1'
    GROUP BY 
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        MAT.DIM_MATERIAL,
        MAT.TXT_MATERIAL
    HAVING SUPPLIER_COUNT > 1
    ORDER BY TOTAL_SPEND DESC
),
PRICE_ARBITRAGE_DATA AS (
SELECT YEAR, CATEGORY, MATERIAL, SUM(PRICE_ARBITRAGE) AS PRICE_ARBITRAGE FROM DATA.T_C_PRICE_ARBITRAGE
WHERE YEAR =  YEAR(CURRENT_DATE) AND LOWER(CATEGORY) =  LOWER('CIBC')
GROUP BY YEAR, CATEGORY, MATERIAL
),
PCM_DATA AS (
SELECT YEAR, CATEGORY, MATERIAL, SUM(CLEANSHEET_OPPORTUNITY) AS CLEANSHEET_OPPORTUNITY FROM DATA.T_C_PARAMETRIC_COST_MODELLING
WHERE YEAR =  YEAR(CURRENT_DATE) AND LOWER(CATEGORY) =  LOWER('CIBC')
GROUP BY YEAR, CATEGORY, MATERIAL
),
LPP_DATA AS (
SELECT YEAR, CATEGORY, MATERIAL, SUM(LPP_CORRUGATES_OPPORTUNITY) AS LPP_CORRUGATES_OPPORTUNITY FROM DATA.T_C_LPP
WHERE YEAR =  YEAR(CURRENT_DATE) AND LOWER(CATEGORY) =  LOWER('CIBC')
GROUP BY YEAR, CATEGORY, MATERIAL
)
SELECT 
    SD.YEAR,
    SD.CATEGORY,
    SD.MATERIAL,
    SUM(GREATEST(COALESCE(PD.PRICE_ARBITRAGE, 0),COALESCE(PC.CLEANSHEET_OPPORTUNITY,0), COALESCE(LP.LPP_CORRUGATES_OPPORTUNITY,0))) AS TOTAL_OPPORTUNITY
FROM SINGLE_SOURCE_MATERIAL_DATA SD
LEFT JOIN PRICE_ARBITRAGE_DATA PD ON SD.YEAR = PD.YEAR AND SD.CATEGORY = PD.CATEGORY AND SD.MATERIAL = PD.MATERIAL
LEFT JOIN PCM_DATA PC ON SD.YEAR = PC.YEAR AND SD.CATEGORY = PC.CATEGORY AND SD.MATERIAL = PC.MATERIAL
LEFT JOIN LPP_DATA LP ON SD.YEAR = LP.YEAR AND SD.CATEGORY = LP.CATEGORY AND SD.MATERIAL = LP.MATERIAL
ORDER BY TOTAL_OPPORTUNITY DESC