SELECT
    YEAR,
    CATEGORY,
    MATERIAL,
    SUPPLIER,
    COUNTRY,
    SUM(SPEND) AS SPEND,
    SUM(CLEANSHEET_OPPORTUNITY) AS CLEANSHEET_OPPORTUNITY,
    AVG(SPEND_SAVINGS_PERCENTAGE) AS SPEND_SAVINGS_PERCENTAGE
FROM
    DATA.T_C_PARAMETRIC_COST_MODELLING
WHERE YEAR = YEAR(CURRENT_DATE)
AND LOWER(CATEGORY) = LOWER('CIBC')
GROUP BY
    YEAR,
    CATEGORY,
    MATERIAL,
    SUPPLIER,
    COUNTRY
ORDER BY 
    YEAR DESC,
    CLEANSHEET_OPPORTUNITY DESC,
    SPEND_SAVINGS_PERCENTAGE DESC