SELECT
    PARENT_SUPPLIER_NAME,
    SUPPLIER_NAME,
    CATEGORY,
    CHANNEL,
    INDUSTRY_NAME,
    TOPIC_NAME,
    TITLE,
    DESCRIPTION,
    URL,
    PUBLISHED_DATE
FROM
    DATA.SUPPLIER_NEWS
ORDER BY PUBLISHED_DATE DESC;