SELECT
    YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')) AS YEAR,
    TXT_CATEGORY AS CATEGORY,
    TXT_BEROE_SUBCATEGORY AS BEROE_CATEGORY,
    TXT_CRITERIA AS CRITERIA,
    MAX(MES_VALUE) AS NET_DEMAND_PERCENTAGE
FROM
    DATA.T_C_MARKET_ANALYSIS
WHERE
    LOWER(TXT_CRITERIA) LIKE LOWER('%Available Net Demand%')
    AND LOWER(TXT_LOCATION) = LOWER('Global')
    AND YEAR (TO_DATE (DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
    AND LOWER(TXT_CATEGORY) = LOWER('Valves')
GROUP BY
    YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')),
    TXT_BEROE_SUBCATEGORY,
    TXT_CATEGORY,
    TXT_CRITERIA