
WITH COUNTRY_SUPPLIER_DATA AS (
    SELECT
        DISTINCT
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS QUARTER,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SC.TXT_COUNTRY AS COUNTRY,
        PL.TXT_PLANT AS PLANT,
        SUP.TXT_SUPPLIER AS SUPPLIER,
    FROM DATA.VT_C_FACT_GRN_ORDERPOSITION GO
    JOIN DATA.VT_DIM_Period PER ON PER.DIM_DATE = GO.DIM_DATE
    JOIN DATA.VT_DIM_PLANT PL ON PL.DIM_PLANT = GO.DIM_PLANT
    JOIN DATA.VT_DIM_SUPPLIERCOUNTRY SC ON SC.DIM_COUNTRY = GO.DIM_COUNTRY
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = GO.DIM_SOURCING_TREE
    JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = GO.DIM_SUPPLIER
    JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = GO.DIM_MATERIAL
    JOIN DATA.VT_C_DIM_ORDERDOCUMENTTYPE ODT ON ODT.DIM_DOCUMENT_TYPE = GO.DIM_DOCUMENT_TYPE
    WHERE PL.TXT_PLANT IN ('Al Taweelah Alumina LLC','Dubai Aluminium PJSC','Emirates Aluminium Company')
        AND ODT.DIM_DOCUMENT_TYPE IN ('DSP100.F.CP','DSP100.F.NB','DSP100.F.ST')
        AND YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = YEAR (CURRENT_DATE)
        AND QUARTER(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = QUARTER (CURRENT_DATE)
        AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Valves')
)
SELECT
    DISTINCT
    SPC.YEAR,
    SPC.QUARTER,
    SPC.CATEGORY,
    SPC.SUPPLIER,
    SPC.SKU,
    SPC.CHANGE_IN_SKU_PRICE_PERCENTAGE,
    SPC.CHANGE_IN_MARKET_PRICE_PERCENTAGE
FROM
    DATA.SKU_PRICE_COMPARISON SPC
JOIN COUNTRY_SUPPLIER_DATA CSD ON
SPC.YEAR = CSD.YEAR AND SPC.QUARTER = CSD.QUARTER AND SPC.CATEGORY = CSD.CATEGORY AND SPC.SUPPLIER = CSD.SUPPLIER
WHERE
    SPC.YEAR = YEAR (CURRENT_DATE)
    AND SPC.QUARTER = QUARTER (CURRENT_DATE)
    AND LOWER(SPC.CATEGORY) = LOWER('Valves')
    AND SPC.CHANGE_IN_SKU_PRICE_PERCENTAGE > SPC.CHANGE_IN_MARKET_PRICE_PERCENTAGE
ORDER BY 
    SPC.CHANGE_IN_SKU_PRICE_PERCENTAGE DESC