WITH SUPPLIER_SPEND AS (
    SELECT 
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        SOUR.TXT_CATEGORY_LEVEL_4 AS SUBCATEGORY, 
        SUP.TXT_CONS_SUPPLIER_L1 AS SUPPLIER_NAME,
        SUM(IVP.MES_SPEND_CURR_1) AS SPEND
    FROM DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
    JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
    JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
    WHERE LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Marketing Svcs')
    AND YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
    GROUP BY 
        YEAR(TO_DATE(PER.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        SOUR.TXT_CATEGORY_LEVEL_4,
        SUP.TXT_CONS_SUPPLIER_L1
),
TOTAL_SPEND AS (
    SELECT 
        YEAR,
        CATEGORY,
        SUBCATEGORY,
        SUM(SPEND) AS TOTAL_SPEND
    FROM SUPPLIER_SPEND
    GROUP BY
        YEAR,
        CATEGORY,
        SUBCATEGORY
),
SUPPLIER_RANKED AS (
    SELECT 
        SUP.YEAR,
        SUP.CATEGORY,
        SUP.SUBCATEGORY,
        SUP.SUPPLIER_NAME,
        SUP.SPEND,
        TOTAL.TOTAL_SPEND,
        SUM(SUP.SPEND) OVER (PARTITION BY SUP.YEAR, SUP.CATEGORY, SUP.SUBCATEGORY ORDER BY SUP.SPEND DESC) AS CUMULATIVE_SPEND,
        SUM(SUP.SPEND) OVER (PARTITION BY SUP.YEAR, SUP.CATEGORY, SUP.SUBCATEGORY ORDER BY SUP.SPEND DESC) / TOTAL.TOTAL_SPEND * 100 AS CUMULATIVE_PERCENTAGE
    FROM SUPPLIER_SPEND SUP
    JOIN TOTAL_SPEND TOTAL ON SUP.YEAR = TOTAL.YEAR AND SUP.CATEGORY = TOTAL.CATEGORY AND SUP.SUBCATEGORY = TOTAL.SUBCATEGORY
)
SELECT 
DISTINCT
    YEAR,
    CATEGORY,
    SUBCATEGORY,
    SPEND AS TOTAL_SPEND,
    SUPPLIER_NAME AS TAIL_SUPPLIERS
FROM SUPPLIER_RANKED
WHERE CUMULATIVE_PERCENTAGE > 80