WITH
    MONTHLY_SPEND AS (
        SELECT
            YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
            MONTH (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS MONTH,
            SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
            SUM(MES_SPEND_CURR_1) AS TOTAL_SPEND
        FROM
            DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
            JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
            JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
        WHERE
            YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
            AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Marketing Svcs')
        GROUP BY
            YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
            MONTH (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
            SOUR.TXT_CATEGORY_LEVEL_2
        ORDER BY
            YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
            MONTH (TO_DATE (PER.DIM_DATE, 'YYYYMMDD'))
    )
SELECT
    YEAR,
    MONTH,
    CATEGORY,
    TOTAL_SPEND AS CURRENT_SPEND,
    LAG (TOTAL_SPEND) OVER (
        PARTITION BY
            CATEGORY
        ORDER BY
            YEAR,
            MONTH
    ) AS PREVIOUS_SPEND,
    ROUND(
        CASE
            WHEN PREVIOUS_SPEND = 0 THEN 0
            ELSE ((TOTAL_SPEND - PREVIOUS_SPEND) / PREVIOUS_SPEND) * 100
        END,
        2
    ) AS MOM_GROWTH_PERCENTAGE
FROM
    MONTHLY_SPEND
ORDER BY
    YEAR,
    MONTH