WITH SupplierSpend AS (
    SELECT
        ct.TXT_CATEGORY_LEVEL_2 AS Category,
        s.TXT_CONS_SUPPLIER_L1,
        SUM(fip.MES_SPEND_CURR_1) AS GroupedSpend
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED fip
        JOIN DATA.VT_DIM_PERIOD p ON fip.DIM_DATE = p.DIM_DATE
        JOIN DATA.VT_C_DIM_SUPPLIER s ON fip.DIM_SUPPLIER = s.DIM_SUPPLIER
        JOIN DATA.VT_DIM_SUPPLIERSTATUS ss ON fip.DIM_SUPPLIER_STATUS = ss.DIM_SUPPLIER_STATUS
        JOIN DATA.VT_C_DIM_VALUETYPE vt ON fip.dim_value_type = vt.DIM_VALUE_TYPE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME ct ON fip.DIM_SOURCING_TREE = ct.DIM_SOURCING_TREE
    WHERE
        YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) = YEAR(DATEADD(YEAR, -2, CURRENT_DATE))
        AND ss.DIM_SUPPLIER_STATUS = 'E'
        AND vt.DIM_VALUE_TYPE = 'I'
        AND ct.TXT_CATEGORY_LEVEL_2 = 'Bearings'
    GROUP BY
        ct.TXT_CATEGORY_LEVEL_2,
        s.TXT_CONS_SUPPLIER_L1
)
SELECT
    Category,
    TXT_CONS_SUPPLIER_L1 AS Supplier,
    GroupedSpend
FROM
    SupplierSpend
ORDER BY
    GroupedSpend DESC