SELECT
DISTINCT
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) AS Year,
	c.TXT_COUNTRY AS Country
FROM
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED f
JOIN data.VT_DIM_Company c ON
	c.DIM_COMPANY = f.DIM_COMPANY
JOIN data.VT_DIM_Period p ON
	p.DIM_DATE = f.DIM_DATE
JOIN data.VT_DIM_SupplierStatus s ON
	s.DIM_SUPPLIER_STATUS = f.DIM_SUPPLIER_STATUS
JOIN data.VT_C_DIM_ValueType v ON
	v.dim_value_type = f.DIM_VALUE_TYPE
JOIN data.VT_C_DIM_SourcingTree_TECHCME ct ON
	ct.DIM_SOURCING_TREE = f.DIM_SOURCING_TREE
WHERE
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) = '2023'
	AND s.DIM_SUPPLIER_STATUS = 'E'
	AND v.DIM_VALUE_TYPE = 'I'
	AND ct.TXT_CATEGORY_LEVEL_2 = 'Bearings'