SELECT
    YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')) AS YEAR,
    CATEGORY AS CATEGORY,
    TXT_GRADE AS ROLE,
    AVG(MES_PRICE_BENCHMARK) AS PRICE
FROM
    DATA.VT_C_FACT_ACTUAL_BILL_RATES
WHERE 
    YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
    AND LOWER(CATEGORY) = LOWER('Marketing Svcs')
GROUP BY
    YEAR(TO_DATE(DIM_DATE, 'YYYYMMDD')),
    CATEGORY,
    TXT_GRADE