SELECT
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) AS Year,
	com.TXT_LEVEL_4 AS Business_Units,
	SUM(f.MES_SPEND_CURR_1) AS TotalSpends
FROM
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED f
JOIN data.VT_DIM_Company com ON
	com.DIM_Company = f.DIM_Company
JOIN data.VT_DIM_Period p ON
	p.DIM_DATE = f.DIM_DATE
JOIN data.VT_DIM_SupplierStatus s ON
	s.DIM_SUPPLIER_STATUS = f.DIM_SUPPLIER_STATUS
JOIN data.VT_C_DIM_ValueType v ON
	v.dim_value_type = f.DIM_VALUE_TYPE
JOIN data.VT_C_DIM_SourcingTree_TECHCME c ON
	c.DIM_SOURCING_TREE = f.DIM_SOURCING_TREE
WHERE
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) = YEAR(CAST(CURRENT_TIMESTAMP AS DATE))
	AND s.DIM_SUPPLIER_STATUS = 'E'
	AND v.DIM_VALUE_TYPE = 'I'
	AND c.TXT_CATEGORY_LEVEL_2 = 'Bearings'
GROUP BY YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')),
	com.TXT_LEVEL_4