WITH TopSupplierData AS (
SELECT
TOP 1
	f.DIM_SUPPLIER,
	ct.TXT_CATEGORY_LEVEL_2 AS Category,
	s.TXT_SUPPLIER AS TopSupplier,
	SUM(f.MES_SPEND_CURR_1) AS Spends,
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) AS Year
FROM
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED f
JOIN data.VT_DIM_Period p ON
	p.DIM_DATE = f.DIM_DATE
JOIN data.VT_C_DIM_Supplier s ON
	s.DIM_SUPPLIER = f.DIM_SUPPLIER
JOIN data.VT_C_DIM_Material m ON
	m.DIM_MATERIAL = f.DIM_MATERIAL 
JOIN data.VT_DIM_SupplierStatus ss ON
	ss.DIM_SUPPLIER_STATUS = f.DIM_SUPPLIER_STATUS
JOIN data.VT_C_DIM_ValueType vt ON
	vt.dim_value_type = f.DIM_VALUE_TYPE
JOIN data.VT_C_DIM_SourcingTree_TECHCME ct ON
	ct.DIM_SOURCING_TREE = f.DIM_SOURCING_TREE
WHERE
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
		AND ss.DIM_SUPPLIER_STATUS = 'E'
		AND vt.DIM_VALUE_TYPE = 'I'
		AND ct.TXT_CATEGORY_LEVEL_2 = 'Bearings'
	GROUP BY
		f.DIM_SUPPLIER,
		s.TXT_SUPPLIER,
		YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')),
		ct.TXT_CATEGORY_LEVEL_2
ORDER BY Spends DESC
)
SELECT
	Year,
	Category,
	TopSupplier,
	m.TXT_MATERIAL AS Material,
	COUNT(f.DIM_MATERIAL)
FROM
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED f
JOIN TopSupplierData tsd ON
	tsd.DIM_SUPPLIER = f.DIM_SUPPLIER 
JOIN data.VT_C_DIM_Material m ON
	m.DIM_MATERIAL = f.DIM_MATERIAL 
GROUP BY Year,
	Category,
	TopSupplier,
	m.TXT_MATERIAL