SELECT
	p.TXT_YEAR AS Year,
	c.TXT_CATEGORY_LEVEL_2 AS Category,
	pl.TXT_PLANT AS Plant,
	SUM(f.MES_SPEND_CURR_1) AS TotalSpend
FROM
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED f
JOIN data.VT_DIM_Period p ON
	p.DIM_DATE = f.DIM_DATE
JOIN data.VT_DIM_SupplierStatus s ON
	s.DIM_SUPPLIER_STATUS = f.DIM_SUPPLIER_STATUS
JOIN data.VT_C_DIM_ValueType v ON
	v.DIM_VALUE_TYPE = f.DIM_VALUE_TYPE
JOIN data.VT_C_DIM_SourcingTree_TECHCME c ON
	c.DIM_SOURCING_TREE = f.DIM_SOURCING_TREE
JOIN data.VT_DIM_Plant pl ON
	pl.DIM_PLANT = f.DIM_PLANT
WHERE
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) = YEAR(CAST('2023' AS DATE))
	AND s.DIM_SUPPLIER_STATUS = 'E'
	AND v.DIM_VALUE_TYPE = 'I'
	AND c.TXT_CATEGORY_LEVEL_2 = 'Bearings'
GROUP BY
	p.TXT_YEAR,
	pl.TXT_PLANT,
	c.TXT_CATEGORY_LEVEL_2
ORDER BY TotalSpend DESC