SELECT
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) AS Year,
	m.TXT_MATERIAL AS Material,
	COUNT(f.DIM_MATERIAL) AS MaterialCount
FROM
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED f
JOIN data.VT_DIM_Period p ON
	f.DIM_DATE = p.DIM_DATE
JOIN data.VT_DIM_SupplierStatus s ON
	f.DIM_SUPPLIER_STATUS = s.DIM_SUPPLIER_STATUS
JOIN data.VT_C_DIM_ValueType v ON
	f.dim_value_type = v.DIM_VALUE_TYPE
JOIN data.VT_C_DIM_Material m ON
	f.DIM_MATERIAL = m.DIM_MATERIAL
JOIN data.VT_C_DIM_SourcingTree_TECHCME c ON
	f.DIM_SOURCING_TREE = c.DIM_SOURCING_TREE
WHERE
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) = YEAR(CAST('2023' AS DATE))
	AND 
        s.DIM_SUPPLIER_STATUS = 'E'
	AND 
        v.DIM_VALUE_TYPE = 'I'
	AND 
        c.TXT_CATEGORY_LEVEL_2 = 'Bearings'
 GROUP BY YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')), m.TXT_MATERIAL 