WITH MaterialSourceSuppliers AS (
SELECT
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED.DIM_SUPPLIER,
	data.VT_DIM_Period.YEAR_OFFSET,
	data.VT_DIM_SupplierStatus.DIM_SUPPLIER_STATUS,
	data.VT_C_DIM_ValueType.DIM_VALUE_TYPE,
	data.VT_C_DIM_Material.TXT_MATERIAL,
	data.VT_C_DIM_SourcingTree_TECHCME.TXT_CATEGORY_LEVEL_2
FROM
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED
 JOIN data.VT_DIM_Period ON
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED.DIM_DATE = data.VT_DIM_Period.DIM_DATE
 JOIN data.VT_DIM_SupplierStatus ON
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED.DIM_SUPPLIER_STATUS = data.VT_DIM_SupplierStatus.DIM_SUPPLIER_STATUS
 JOIN data.VT_C_DIM_ValueType ON
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED.dim_value_type = data.VT_C_DIM_ValueType.DIM_VALUE_TYPE
 JOIN data.VT_C_DIM_Material ON
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED.DIM_MATERIAL = data.VT_C_DIM_Material.DIM_MATERIAL
 JOIN data.VT_C_DIM_SourcingTree_TECHCME ON
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED.DIM_SOURCING_TREE = data.VT_C_DIM_SourcingTree_TECHCME.DIM_SOURCING_TREE
WHERE
	year(to_date(data.VT_DIM_Period.DIM_DATE,'YYYYMMDD')) = year(current_date)
	AND 
        data.VT_DIM_SupplierStatus.DIM_SUPPLIER_STATUS = 'E'
	AND 
        data.VT_C_DIM_ValueType.DIM_VALUE_TYPE = 'I'
	AND 
        data.VT_C_DIM_Material.TXT_MATERIAL = 'Machining BC 2399'
	AND 
        data.VT_C_DIM_SourcingTree_TECHCME.TXT_CATEGORY_LEVEL_2 = 'Bearings' 
)
SELECT
	COUNT(DISTINCT DIM_SUPPLIER) AS Suppliers_Count
FROM
	MaterialSourceSuppliers 