WITH MATERIAL_DATA AS (
    SELECT
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
        SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
        COUNT(DISTINCT IVP.DIM_SUPPLIER) AS SUPPLIER_COUNT,
        MAT.DIM_MATERIAL AS MATERIAL_ID,
        SUM(MES_SPEND_CURR_1) AS TOTAL_SPEND
    FROM
        DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
        JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
        JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
        JOIN DATA.VT_C_DIM_SUPPLIER SUP ON SUP.DIM_SUPPLIER = IVP.DIM_SUPPLIER
        JOIN DATA.VT_C_DIM_MATERIAL MAT ON MAT.DIM_MATERIAL = IVP.DIM_MATERIAL
    WHERE
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
         AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Bearings')
         AND MAT.DIM_MATERIAL != '-1'
    GROUP BY 
        YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
        SOUR.TXT_CATEGORY_LEVEL_2,
        MAT.DIM_MATERIAL
)
SELECT 
    YEAR,
    CATEGORY,
    COUNT(CASE WHEN SUPPLIER_COUNT > 1 THEN MATERIAL_ID END) AS SINGLE_SOURCE_COUNT,
    COUNT(MATERIAL_ID) AS MATERIAL_COUNT,
    ROUND((COUNT(CASE WHEN SUPPLIER_COUNT > 1 THEN MATERIAL_ID END)/COUNT(MATERIAL_ID))*100,2) AS MULTI_SOURCE_MATERIAL_PERCENTAGE,
    ROUND(SUM(CASE WHEN SUPPLIER_COUNT > 1 THEN TOTAL_SPEND ELSE 0 END),2) AS SINGLE_SOURCE_SPEND,
    ROUND(SUM(TOTAL_SPEND),2) AS TOTAL_SPEND,
    ROUND((SUM(CASE WHEN SUPPLIER_COUNT > 1 THEN TOTAL_SPEND ELSE 0 END)/SUM(TOTAL_SPEND))*100,2) AS MULTI_SOURCE_SPENDL_PERCENTAGE
FROM MATERIAL_DATA
GROUP BY YEAR,
    CATEGORY
ORDER BY SINGLE_SOURCE_SPEND DESC;