SELECT
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) AS SelectedYear,
	ct.TXT_CATEGORY_LEVEL_2 AS Category,
	m.TXT_Material AS SKU,
	COUNT(fip.DIM_MATERIAL) AS SKU_Count
FROM
	data.VT_C_FACT_INVOICEPOSITION_MULTIPLIED fip
JOIN 
        data.VT_DIM_Period p ON
	p.DIM_DATE = fip.DIM_DATE
JOIN 
        data.VT_DIM_SupplierStatus ss ON
	ss.DIM_SUPPLIER_STATUS = fip.DIM_SUPPLIER_STATUS
JOIN 
        data.VT_C_DIM_ValueType vt ON
	vt.DIM_VALUE_TYPE = fip.dim_value_type
JOIN 
        data.VT_C_DIM_Material m ON
	m.DIM_MATERIAL = fip.DIM_MATERIAL
JOIN 
        data.VT_C_DIM_SourcingTree_TECHCME ct ON
	ct.DIM_SOURCING_TREE = fip.DIM_SOURCING_TREE
WHERE
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_TIMESTAMP)
	AND
        ss.DIM_SUPPLIER_STATUS = 'E'
	AND 
        vt.DIM_VALUE_TYPE = 'I'
	AND 
        m.DIM_MATERIAL IS NOT NULL
	AND 
        ct.TXT_CATEGORY_LEVEL_2 = 'Bearings'
GROUP BY
	ct.TXT_CATEGORY_LEVEL_2,
	YEAR(TO_DATE(p.DIM_DATE, 'YYYYMMDD')),
	m.TXT_Material