SELECT
    YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) AS YEAR,
    SOUR.TXT_CATEGORY_LEVEL_2 AS CATEGORY,
    SOUR.TXT_CATEGORY_LEVEL_3 AS SUBCATEGORY,
    SUM(MES_SPEND_CURR_1) AS TOTAL_SPEND
FROM
    DATA.VT_C_FACT_INVOICEPOSITION_MULTIPLIED IVP
    JOIN DATA.VT_DIM_PERIOD PER ON PER.DIM_DATE = IVP.DIM_DATE
    JOIN DATA.VT_C_DIM_SOURCINGTREE_TECHCME SOUR ON SOUR.DIM_SOURCING_TREE = IVP.DIM_SOURCING_TREE
WHERE
   YEAR (TO_DATE (PER.DIM_DATE, 'YYYYMMDD')) = YEAR(CURRENT_DATE)
    AND LOWER(SOUR.TXT_CATEGORY_LEVEL_2) = LOWER('Marketing Svcs')
    AND  LOWER(SOUR.TXT_CATEGORY_LEVEL_3) = LOWER('Non-working')
GROUP BY
    YEAR(TO_DATE (PER.DIM_DATE, 'YYYYMMDD')),
    SOUR.TXT_CATEGORY_LEVEL_2,
    SOUR.TXT_CATEGORY_LEVEL_3
ORDER BY TOTAL_SPEND DESC