---
global:
  workspace_name: "aza-ml-f033d33"
  subscription_id: "5a911952-52ae-4144-b0f4-63293a775c3b"
  resource_group: "sourceaigenaide-f033d33"
  msi_client_id: "bdbecb26-5ca4-4f28-a7cb-50d170178a22"
  sp_client_id: "7018a783-3a9f-4886-b621-305c9ad62934"
  azure_tenant_id: "b0257c14-cacc-44c6-8927-5b4ce5de0874"

static_deployment_conf:
  # NOTE: You cannot update an instance type without deleting the resource.
  instance_type: "Standard_DS2_v2"
  instance_count: 1
  request_timeout_ms: 180000
  max_queue_wait_ms: 180000
  max_concurrent_requests_per_instance: 12
  readiness_timeout_seconds: 90
  liveness_timeout_seconds: 90
  app_insights_enabled: true
  db_migrate_compute_target: "CPU-DS2-v2"

endpoints:
  - name: "sps-data-retrieval-dev"
    deploy_endpoint: true
    deploy_deployment: true
    env_name: "orp-genai-conda"
    entrypoint: "src/ada/azml_realtime_deployments/document_service_deployment.py"

  - name: "sps-data-retrieval-service-dev"
    deploy_endpoint: true
    deploy_deployment: true
    env_name: "orp-genai-conda"
    entrypoint: "src/ada/azml_realtime_deployments/data_retrieval_service_deployment.py"

  - name: "sps-contract-preprocessing-dev"
    deploy_endpoint: true
    deploy_deployment: true
    env_name: "orp-genai-conda"
    entrypoint: "src/ada/azml_realtime_deployments/preprocessing_deployment.py"
    job_params:
      datastore: "workspaceblobstore"
      compute: "CPU-DS2-v2"

  - name: "sps-leakage-extraction-dev"
    deploy_endpoint: true
    deploy_deployment: true
    env_name: "orp-genai-conda"
    entrypoint: "src/ada/azml_realtime_deployments/leakage_extraction_deployment.py"

  - name: "sps-unified-model-dev"
    deploy_endpoint: true
    deploy_deployment: true
    env_name: "orp-genai-conda"
    entrypoint: "src/ada/azml_realtime_deployments/intent_model_v2_deployment.py"
    override_deployment_conf:
      max_concurrent_requests_per_instance: 8
      instance_type: "Standard_DS4_v2"
      liveness_timeout_seconds: 180

  - name: "sps-ppt-generation-dev"
    deploy_endpoint: true
    deploy_deployment: true
    env_name: "orp-genai-conda"
    entrypoint: "src/ada/azml_realtime_deployments/ppt_generation_deployment.py"
    override_deployment_conf:
      max_concurrent_requests_per_instance: 8
      instance_type: "Standard_DS4_v2"
      liveness_timeout_seconds: 180

  - name: "sps-top-ideas-dev"
    deploy_endpoint: true
    deploy_deployment: true
    env_name: "orp-genai-conda"
    entrypoint: "src/ada/azml_realtime_deployments/top_idea_deployment.py"

components:
  preprocessing_dev:
    component_name: "preprocessing_dev"
    register: true
    source: "src/ada/azml_components/pipeline_dev.yml"
models:
  contract_qna_classifier:
    model_name: "contract_question_model_dev"
    register: true
    source: "contract_qna_classifier_model.pkl"
    description: "custom model to classify contract question"
    version: 3
    training_data: "data/contract_qna/contract_question_classification_data.csv"
    encoding: 'utf-8'
    training_column: "question"
    class_column: "category"
    embedding:
      embedding_model: "sentence-transformers/bert-base-nli-mean-tokens"
      tokenizer: "sentence-transformers/bert-base-nli-mean-tokens"
      embedding_model_type: "bert"
    model_function_name: "voting_classifier"
    rf_params:
      n_estimators: 100
      max_depth: 8
      min_samples_split: 2
    svc_params:
      kernel: "linear"
      probability: true


base_endpoint_url: https://endpoint-name.westus.inference.ml.azure.com/score
