SELECT
    YEAR(TO_DATE (DIM_DATE, 'YYYYMMDD')) AS YEAR,
    TXT_CATEGORY AS CATEGORY,   
    TXT_BEROE_SUBCATEGORY AS CATEGORY,
    TXT_CRITERIA AS CRITERIA,
    CONCAT(MAX(MES_VALUE), ' B') AS GROWTH_RATE
FROM
    DATA.T_C_MARKET_ANALYSIS MA
WHERE
    LOWER(TXT_CRITERIA) LIKE LOWER('%Growth Rate%')
    AND LOWER(TXT_LOCATION) = LOWER('Global')
    AND YEAR(TO_DATE (DIM_DATE, 'YYYYMMDD'))  = YEAR(CURRENT_DATE)
    AND QUARTER(TO_DATE (DIM_DATE, 'YYYYMMDD'))  = QUARTER(CURRENT_DATE)
    AND LOWER(TXT_CATEGORY) = LOWER('Valves')
GROUP BY
    YEAR(TO_DATE (DIM_DATE, 'YYYYMMDD')),
    TXT_BEROE_SUBCATEGORY,
    TXT_CATEGORY,
    TXT_CRITERIA